# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_telecom.Line_HouseMode
#
# * primary keys: PK_Line_HouseMode
# * foreign keys: 
# * external keys: EK_HouseMode
#
# == References
#
# == Referenced By
#
# == Database Table Columns
#   * PK_Line_HouseMode    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * ID                   [Type:int(11), Default:NULL, Null:YES]
#   * Type                 [Type:varchar(50), Default:NULL, Null:YES]
#   * EK_HouseMode         [Type:int(11), Default:NULL, Null:YES]
#   * Routing              [Type:text, Default:NULL, Null:YES]
#   * psc_id               [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch            [Type:int(11), Default:NULL, Null:YES]
#   * psc_user             [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod              [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict         [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_house_mode
#

require 'pluto_main/lmce_house_mode'

include PlutoMain

class PlutoTelecom::LmceLineHouseMode < PlutoTelecomDatabase
  set_table_name "Line_HouseMode"
  set_primary_key "PK_Line_HouseMode"

  # external key references
  # EK_Line_HouseMode references PlutoMain::LmceHouseMode (EK_HouseMode)
  belongs_to  :lmce_house_mode,
      :class_name => "PlutoMain::LmceHouseMode",
      :foreign_key => "EK_HouseMode"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

