# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_telecom.IncomingLog
#
# * primary keys: PK_IncomingLog
# * foreign keys: FK_PhoneNumber
# * external keys: 
#
# == References
# * PlutoTelecom::LmcePhoneNumber
#
# == Referenced By
#
# == Database Table Columns
#   * PK_IncomingLog    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * DateTime          [Type:datetime, Default:NULL, Null:YES]
#   * FK_PhoneNumber    [Type:int(11), Default:NULL, Null:YES]
#   * PhoneNumber       [Type:varchar(30), Default:NULL, Null:YES]
#   * Duration          [Type:int(11), Default:NULL, Null:YES]
#   * Answered          [Type:tinyint(1), Default:0, Null:YES]
#   * Voicemail         [Type:tinyint(1), Default:0, Null:YES]
#   * psc_id            [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch         [Type:int(11), Default:NULL, Null:YES]
#   * psc_user          [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen        [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod           [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict      [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_phone_number
#

class PlutoTelecom::LmceIncomingLog < PlutoTelecomDatabase
  set_table_name "IncomingLog"
  set_primary_key "PK_IncomingLog"

  # foreign key references
  # FK_IncomingLog references PlutoTelecom::LmcePhoneNumber (FK_PhoneNumber)
  belongs_to  :lmce_phone_number,
      :class_name => "PlutoTelecom::LmcePhoneNumber",
      :foreign_key => "FK_PhoneNumber"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

