# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_telecom.psc_telecom_batuser
#
# * primary keys: PK_psc_telecom_batuser
# * foreign keys: FK_psc_telecom_bathdr
# * external keys: 
#
# == References
# * PlutoTelecom::LmcePscTelecomBathdr
#
# == Referenced By
#
# == Database Table Columns
#   * PK_psc_telecom_batuser    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_psc_telecom_bathdr     [Type:int(11), Default:0, Null:NO]
#   * psc_user                  [Type:int(11), Default:0, Null:NO]
#   * is_sup                    [Type:tinyint(1), Default:0, Null:NO]
#   * no_pass                   [Type:tinyint(1), Default:0, Null:NO]
#
# == Associations
# * belongs_to lmce_psc_telecom_bathdr
#

class PlutoTelecom::LmcePscTelecomBatuser < PlutoTelecomDatabase
  set_table_name "psc_telecom_batuser"
  set_primary_key "PK_psc_telecom_batuser"

  # foreign key references
  # FK_psc_telecom_batuser references PlutoTelecom::LmcePscTelecomBathdr (FK_psc_telecom_bathdr)
  belongs_to  :lmce_psc_telecom_bathdr,
      :class_name => "PlutoTelecom::LmcePscTelecomBathdr",
      :foreign_key => "FK_psc_telecom_bathdr"


  # add your model extensions after this line

end

