# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.EffectType_Effect_Skin
# Through Join Table
#
# * primary keys: FK_EffectType,FK_Effect,FK_Skin
# * foreign keys: FK_EffectType,FK_Effect,FK_Skin
# * external keys: 
#
# == References
# * PlutoMain::LmceEffect
# * PlutoMain::LmceEffectType
# * PlutoMain::LmceSkin
#
# == Referenced By
#
# == Database Table Columns
#   * FK_EffectType    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Effect        [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Skin          [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * psc_id           [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch        [Type:int(11), Default:NULL, Null:YES]
#   * psc_user         [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen       [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod          [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict     [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_effect
# * belongs_to lmce_effect_type
# * belongs_to lmce_skin
#

class PlutoMain::LmceEffectTypeEffectSkin < PlutoMainDatabase
  set_table_name "EffectType_Effect_Skin"
  set_primary_keys "FK_EffectType", "FK_Effect", "FK_Skin"

  # foreign key references
  # FK_EffectType_Effect_Skin references PlutoMain::LmceEffect (FK_Effect)
  belongs_to  :lmce_effect,
      :class_name => "PlutoMain::LmceEffect",
      :foreign_key => "FK_Effect"

  # FK_EffectType_Effect_Skin references PlutoMain::LmceEffectType (FK_EffectType)
  belongs_to  :lmce_effect_type,
      :class_name => "PlutoMain::LmceEffectType",
      :foreign_key => "FK_EffectType"

  # FK_EffectType_Effect_Skin references PlutoMain::LmceSkin (FK_Skin)
  belongs_to  :lmce_skin,
      :class_name => "PlutoMain::LmceSkin",
      :foreign_key => "FK_Skin"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

