# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DesignObjVariation_DesignObj_Skin_Language
#
# * primary keys: PK_DesignObjVariation_DesignObj_Skin_Language
# * foreign keys: FK_DesignObjVariation_DesignObj,FK_Skin,FK_Language,FK_DesignObj_InsteadOf,FK_DesignObj_Up,FK_DesignObj_Down,FK_DesignObj_Left,FK_DesignObj_Right
# * external keys: 
#
# == References
# * PlutoMain::LmceLanguage
# * PlutoMain::LmceSkin
# * PlutoMain::LmceDesignObjVariationDesignObj
#
# == Referenced By
#
# == Database Table Columns
#   * PK_DesignObjVariation_DesignObj_Skin_Language    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_DesignObjVariation_DesignObj                  [Type:int(11), Default:NULL, Null:YES]
#   * FK_Skin                                          [Type:int(11), Default:NULL, Null:YES]
#   * FK_Language                                      [Type:int(11), Default:NULL, Null:YES]
#   * DisplayOrder                                     [Type:int(11), Default:0, Null:NO]
#   * X                                                [Type:int(11), Default:0, Null:NO]
#   * Y                                                [Type:int(11), Default:0, Null:NO]
#   * Width                                            [Type:int(11), Default:NULL, Null:YES]
#   * Height                                           [Type:int(11), Default:NULL, Null:YES]
#   * FK_DesignObj_InsteadOf                           [Type:int(11), Default:NULL, Null:YES]
#   * CanBeHidden                                      [Type:tinyint(4), Default:0, Null:NO]
#   * HideByDefault                                    [Type:tinyint(4), Default:0, Null:NO]
#   * RegenerateForEachScreen                          [Type:tinyint(4), Default:0, Null:NO]
#   * DisplayChildrenBeforeText                        [Type:tinyint(4), Default:0, Null:NO]
#   * DisplayChildrenBehindBackground                  [Type:tinyint(4), Default:0, Null:NO]
#   * DontMergeBackground                              [Type:tinyint(4), Default:0, Null:NO]
#   * IsTabStop                                        [Type:tinyint(4), Default:0, Null:NO]
#   * FK_DesignObj_Up                                  [Type:int(11), Default:NULL, Null:YES]
#   * FK_DesignObj_Down                                [Type:int(11), Default:NULL, Null:YES]
#   * FK_DesignObj_Left                                [Type:int(11), Default:NULL, Null:YES]
#   * FK_DesignObj_Right                               [Type:int(11), Default:NULL, Null:YES]
#   * sFK_DesignObj_TiedTo                             [Type:varchar(14), Default:NULL, Null:YES]
#   * VisibleStates                                    [Type:varchar(10), Default:NULL, Null:YES]
#   * Ignore                                           [Type:tinyint(1), Default:0, Null:NO]
#   * psc_id                                           [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch                                        [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                                         [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                                       [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                                          [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                                     [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_design_obj_variation_design_obj
# * belongs_to lmce_language
# * belongs_to lmce_skin
#

class PlutoMain::LmceDesignObjVariationDesignObjSkinLanguage < PlutoMainDatabase
  set_table_name "DesignObjVariation_DesignObj_Skin_Language"
  set_primary_key "PK_DesignObjVariation_DesignObj_Skin_Language"

  # foreign key references
  # FK_DesignObjVariation_DesignObj_Skin_Language references PlutoMain::LmceLanguage (FK_Language)
  belongs_to  :lmce_language,
      :class_name => "PlutoMain::LmceLanguage",
      :foreign_key => "FK_Language"

  # FK_DesignObjVariation_DesignObj_Skin_Language references PlutoMain::LmceSkin (FK_Skin)
  belongs_to  :lmce_skin,
      :class_name => "PlutoMain::LmceSkin",
      :foreign_key => "FK_Skin"

  # FK_DesignObjVariation_DesignObj_Skin_Language references PlutoMain::LmceDesignObjVariationDesignObj (FK_DesignObjVariation_DesignObj)
  belongs_to  :lmce_design_obj_variation_design_obj,
      :class_name => "PlutoMain::LmceDesignObjVariationDesignObj",
      :foreign_key => "FK_DesignObjVariation_DesignObj"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

