# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Household_Installation
# Through Join Table
#
# * primary keys: FK_Household,FK_Installation
# * foreign keys: FK_Household,FK_Installation
# * external keys: 
#
# == References
# * PlutoMain::LmceHousehold
# * PlutoMain::LmceInstallation
#
# == Referenced By
#
# == Database Table Columns
#   * FK_Household       [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Installation    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * psc_id             [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch          [Type:int(11), Default:NULL, Null:YES]
#   * psc_user           [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen         [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod            [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict       [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_household
# * belongs_to lmce_installation
#

class PlutoMain::LmceHouseholdInstallation < PlutoMainDatabase
  set_table_name "Household_Installation"
  set_primary_keys "FK_Household", "FK_Installation"

  # foreign key references
  # FK_Household_Installation references PlutoMain::LmceHousehold (FK_Household)
  belongs_to  :lmce_household,
      :class_name => "PlutoMain::LmceHousehold",
      :foreign_key => "FK_Household"

  # FK_Household_Installation references PlutoMain::LmceInstallation (FK_Installation)
  belongs_to  :lmce_installation,
      :class_name => "PlutoMain::LmceInstallation",
      :foreign_key => "FK_Installation"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

