# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DeviceTemplate_DeviceTemplate_Related
# Through Join Table
#
# * primary keys: PK_DeviceTemplate_DeviceTemplate_Related
# * foreign keys: FK_DeviceTemplate,FK_DeviceTemplate_Related
# * external keys: 
#
# == References
# * PlutoMain::LmceDeviceTemplate
#
# == Referenced By
#
# == Database Table Columns
#   * PK_DeviceTemplate_DeviceTemplate_Related    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_DeviceTemplate                           [Type:int(11), Default:0, Null:NO]
#   * FK_DeviceTemplate_Related                   [Type:int(11), Default:0, Null:NO]
#   * Value                                       [Type:text, Default:NULL, Null:YES]
#   * psc_id                                      [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                                   [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                                    [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                                  [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                                     [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                                [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device_template
#

class PlutoMain::LmceDeviceTemplateDeviceTemplateRelated < PlutoMainDatabase
  set_table_name "DeviceTemplate_DeviceTemplate_Related"
  set_primary_key "PK_DeviceTemplate_DeviceTemplate_Related"

  # foreign key references
  # FK_DeviceTemplate_DeviceTemplate_Related references PlutoMain::LmceDeviceTemplate (FK_DeviceTemplate)
  belongs_to  :lmce_device_template,
      :class_name => "PlutoMain::LmceDeviceTemplate",
      :foreign_key => "FK_DeviceTemplate"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

