# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Country
#
# * primary keys: PK_Country
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmcePostalCode
# * PlutoMain::LmceRepositorySourceUrl
# * PlutoMain::LmceRegion
# * PlutoMain::LmceCity
# * PlutoMain::LmceInstallation
#
# == Database Table Columns
#   * PK_Country       [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description      [Type:varchar(30), Null:NO]
#   * Define           [Type:varchar(30), Null:NO]
#   * UsePostalCode    [Type:tinyint(1), Default:0, Null:NO]
#   * country_code     [Type:varchar(5), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_cities
# * has_many lmce_installations
# * has_many lmce_postal_codes
# * has_many lmce_provider_sources
# * has_many lmce_regions
# * has_many lmce_repository_source_urls
#

require 'pluto_media/lmce_provider_source'

include PlutoMedia

class PlutoMain::LmceCountry < PlutoMainDatabase
  set_table_name "Country"
  set_primary_key "PK_Country"

  # foreign key references
  # 1:n  (FK_Country)
  has_many  :lmce_postal_codes,
      :class_name => "PlutoMain::LmcePostalCode",
      :foreign_key => "FK_Country"

  # 1:n  (FK_Country)
  has_many  :lmce_repository_source_urls,
      :class_name => "PlutoMain::LmceRepositorySourceUrl",
      :foreign_key => "FK_Country"

  # 1:n  (FK_Country)
  has_many  :lmce_regions,
      :class_name => "PlutoMain::LmceRegion",
      :foreign_key => "FK_Country"

  # 1:n  (FK_Country)
  has_many  :lmce_cities,
      :class_name => "PlutoMain::LmceCity",
      :foreign_key => "FK_Country"

  # 1:n  (FK_Country)
  has_many  :lmce_installations,
      :class_name => "PlutoMain::LmceInstallation",
      :foreign_key => "FK_Country"

  # external key references
  # 1:n  (EK_Country)
  has_many  :lmce_provider_sources,
      :class_name => "PlutoMedia::LmceProviderSource",
      :foreign_key => "EK_Country"


  # add your model extensions after this line

end

