# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Device_StartupScript
# Through Join Table
#
# * primary keys: FK_Device,FK_StartupScript
# * foreign keys: FK_Device,FK_StartupScript
# * external keys: 
#
# == References
# * PlutoMain::LmceStartupScript
# * PlutoMain::LmceDevice
#
# == Referenced By
#
# == Database Table Columns
#   * FK_Device           [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_StartupScript    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * Boot_Order          [Type:int(11), Default:99, Null:NO]
#   * Background          [Type:tinyint(1), Default:0, Null:NO]
#   * Enabled             [Type:tinyint(1), Default:0, Null:NO]
#   * Parameter           [Type:varchar(50), Default:NULL, Null:YES]
#   * psc_id              [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch           [Type:int(11), Default:NULL, Null:YES]
#   * psc_user            [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen          [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod             [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict        [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device
# * belongs_to lmce_startup_script
#

class PlutoMain::LmceDeviceStartupScript < PlutoMainDatabase
  set_table_name "Device_StartupScript"
  set_primary_keys "FK_Device", "FK_StartupScript"

  # foreign key references
  # FK_Device_StartupScript references PlutoMain::LmceStartupScript (FK_StartupScript)
  belongs_to  :lmce_startup_script,
      :class_name => "PlutoMain::LmceStartupScript",
      :foreign_key => "FK_StartupScript"

  # FK_Device_StartupScript references PlutoMain::LmceDevice (FK_Device)
  belongs_to  :lmce_device,
      :class_name => "PlutoMain::LmceDevice",
      :foreign_key => "FK_Device"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

