# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DesignObjParameter
#
# * primary keys: PK_DesignObjParameter
# * foreign keys: FK_ParameterType
# * external keys: 
#
# == References
# * PlutoMain::LmceParameterType
#
# == Referenced By
# * PlutoMain::LmceDesignObjTypeDesignObjParameter
# * PlutoMain::LmceDesignObjVariationDesignObjParameter
#
# == Database Table Columns
#   * PK_DesignObjParameter    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Define                   [Type:varchar(20), Default:NULL, Null:NO]
#   * Comments                 [Type:varchar(255), Default:NULL, Null:YES]
#   * Description              [Type:varchar(20), Default:NULL, Null:NO]
#   * FK_ParameterType         [Type:int(11), Default:0, Null:NO]
#   * psc_id                   [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                 [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen               [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                  [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict             [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_parameter_type
# * has_many lmce_design_obj_type_design_obj_parameters
# * has_many lmce_design_obj_types
# * has_many lmce_design_obj_variation_design_obj_parameters
# * has_many lmce_design_obj_variations
#

class PlutoMain::LmceDesignObjParameter < PlutoMainDatabase
  set_table_name "DesignObjParameter"
  set_primary_key "PK_DesignObjParameter"

  # foreign key references
  # FK_DesignObjParameter references PlutoMain::LmceParameterType (FK_ParameterType)
  belongs_to  :lmce_parameter_type,
      :class_name => "PlutoMain::LmceParameterType",
      :foreign_key => "FK_ParameterType"

  # n:n via through join table PlutoMain::LmceDesignObjTypeDesignObjParameter  (FK_DesignObjParameter)
  has_many  :lmce_design_obj_type_design_obj_parameters,
      :class_name => "PlutoMain::LmceDesignObjTypeDesignObjParameter",
      :foreign_key => "FK_DesignObjParameter"
  has_many  :lmce_design_obj_types,
      :through => :lmce_design_obj_type_design_obj_parameters

  # n:n via through join table PlutoMain::LmceDesignObjVariationDesignObjParameter  (FK_DesignObjParameter)
  has_many  :lmce_design_obj_variation_design_obj_parameters,
      :class_name => "PlutoMain::LmceDesignObjVariationDesignObjParameter",
      :foreign_key => "FK_DesignObjParameter"
  has_many  :lmce_design_obj_variations,
      :through => :lmce_design_obj_variation_design_obj_parameters

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

