# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Users
#
# * primary keys: PK_Users
# * foreign keys: FK_Language,FK_Installation_Main,FK_UserMode
# * external keys: EK_Dealer,EK_Manufacturer
#
# == References
# * PlutoMain::LmceLanguage
# * PlutoMain::LmceUserMode
#
# == Referenced By
# * PlutoMain::LmcePackageUser
# * PlutoMain::LmceOrbiterUsersPasswordReq
# * PlutoMain::LmceDocumentComment
# * PlutoMain::LmceDeviceUser
# * PlutoMain::LmceInstallationUser
# * PlutoMain::LmceRoomUser
#
# == Database Table Columns
#   * PK_Users                [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * UserName                [Type:varchar(25), Default:NULL, Null:NO]
#   * Password                [Type:varchar(32), Default:NULL, Null:NO]
#   * PINCode                 [Type:varchar(32), Default:0, Null:NO]
#   * HasMailbox              [Type:tinyint(4), Default:0, Null:NO]
#   * AccessGeneralMailbox    [Type:tinyint(4), Default:0, Null:NO]
#   * Extension               [Type:int(11), Default:NULL, Null:YES]
#   * FirstName               [Type:varchar(20), Default:NULL, Null:YES]
#   * LastName                [Type:varchar(30), Default:NULL, Null:YES]
#   * Nickname                [Type:varchar(15), Default:NULL, Null:YES]
#   * ExtensionRingTimeout    [Type:int(11), Default:0, Null:NO]
#   * ForwardEmail            [Type:varchar(50), Default:NULL, Null:YES]
#   * FK_Language             [Type:smallint(5), Default:NULL, Null:YES]
#   * FK_Installation_Main    [Type:int(11), Default:NULL, Null:YES]
#   * HideFromOrbiter         [Type:tinyint(1), Default:0, Null:NO]
#   * Staff                   [Type:tinyint(1), Default:NULL, Null:YES]
#   * Password_Unix           [Type:varchar(100), Default:NULL, Null:YES]
#   * Password_Samba          [Type:varchar(100), Default:NULL, Null:YES]
#   * FK_UserMode             [Type:int(11), Default:1, Null:NO]
#   * EK_Dealer               [Type:int(11), Default:NULL, Null:YES]
#   * EK_Manufacturer         [Type:int(11), Default:NULL, Null:YES]
#   * RequirePinToSelect      [Type:tinyint(1), Default:0, Null:NO]
#   * psc_id                  [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch               [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen              [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                 [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict            [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_language
# * belongs_to lmce_manufacturer
# * belongs_to lmce_user_mode
# * has_many lmce_alerts
# * has_many lmce_bookmarks
# * has_many lmce_device_users
# * has_many lmce_devices
# * has_many lmce_disc_users
# * has_many lmce_discs
# * has_many lmce_document_comments
# * has_many lmce_file_users
# * has_many lmce_files
# * has_many lmce_installation_users
# * has_many lmce_installations
# * has_many lmce_mode_changes
# * has_many lmce_orbiter_users_password_reqs
# * has_many lmce_orbiters
# * has_many lmce_package_users
# * has_many lmce_packages
# * has_many lmce_room_users
# * has_many lmce_rooms
# * has_many lmce_users_private
# * has_many lmce_users_private
#

require 'pluto_main/lmce_manufacturer'
require 'pluto_media/lmce_bookmark'
require 'pluto_media/lmce_disc'
require 'pluto_media/lmce_disc_user'
require 'pluto_media/lmce_file'
require 'pluto_media/lmce_file_user'
require 'pluto_security/lmce_alert'
require 'pluto_security/lmce_mode_change'

include PlutoMain
include PlutoMedia
include PlutoSecurity

class PlutoMain::LmceUser < PlutoMainDatabase
  set_table_name "Users"
  set_primary_key "PK_Users"

  # foreign key references
  # FK_Users references PlutoMain::LmceLanguage (FK_Language)
  belongs_to  :lmce_language,
      :class_name => "PlutoMain::LmceLanguage",
      :foreign_key => "FK_Language"

  # FK_Users references PlutoMain::LmceUserMode (FK_UserMode)
  belongs_to  :lmce_user_mode,
      :class_name => "PlutoMain::LmceUserMode",
      :foreign_key => "FK_UserMode"

  # n:n via through join table PlutoMain::LmcePackageUser  (FK_Users)
  has_many  :lmce_package_users,
      :class_name => "PlutoMain::LmcePackageUser",
      :foreign_key => "FK_Users"
  has_many  :lmce_packages,
      :through => :lmce_package_users

  # n:n via through join table PlutoMain::LmceOrbiterUsersPasswordReq  (FK_Users)
  has_many  :lmce_orbiter_users_password_reqs,
      :class_name => "PlutoMain::LmceOrbiterUsersPasswordReq",
      :foreign_key => "FK_Users"
  has_many  :lmce_orbiters,
      :through => :lmce_orbiter_users_password_reqs

  # 1:n  (FK_Users)
  has_many  :lmce_document_comments,
      :class_name => "PlutoMain::LmceDocumentComment",
      :foreign_key => "FK_Users"

  # n:n via through join table PlutoMain::LmceDeviceUser  (FK_Users)
  has_many  :lmce_device_users,
      :class_name => "PlutoMain::LmceDeviceUser",
      :foreign_key => "FK_Users"
  has_many  :lmce_devices,
      :through => :lmce_device_users

  # n:n via through join table PlutoMain::LmceInstallationUser  (FK_Users)
  has_many  :lmce_installation_users,
      :class_name => "PlutoMain::LmceInstallationUser",
      :foreign_key => "FK_Users"
  has_many  :lmce_installations,
      :through => :lmce_installation_users

  # n:n via through join table PlutoMain::LmceRoomUser  (FK_Users)
  has_many  :lmce_room_users,
      :class_name => "PlutoMain::LmceRoomUser",
      :foreign_key => "FK_Users"
  has_many  :lmce_rooms,
      :through => :lmce_room_users

  # external key references
  # EK_Users references PlutoMain::LmceManufacturer (EK_Manufacturer)
  belongs_to  :lmce_manufacturer,
      :class_name => "PlutoMain::LmceManufacturer",
      :foreign_key => "EK_Manufacturer"

  # n:n via through join table PlutoMedia::LmceFileUser  (EK_Users)
  has_many  :lmce_file_users,
      :class_name => "PlutoMedia::LmceFileUser",
      :foreign_key => "EK_Users"
  has_many  :lmce_files,
      :through => :lmce_file_users

  # 1:n  (EK_Users)
  has_many  :lmce_mode_changes,
      :class_name => "PlutoSecurity::LmceModeChange",
      :foreign_key => "EK_Users"

  # 1:n  (EK_Users)
  has_many  :lmce_alerts,
      :class_name => "PlutoSecurity::LmceAlert",
      :foreign_key => "EK_Users"

  # 1:n  (EK_Users_Private)
  has_many  :lmce_users_private,
      :class_name => "PlutoMedia::LmceFile",
      :foreign_key => "EK_Users_Private"

  # n:n via through join table PlutoMedia::LmceDiscUser  (EK_Users)
  has_many  :lmce_disc_users,
      :class_name => "PlutoMedia::LmceDiscUser",
      :foreign_key => "EK_Users"
  has_many  :lmce_discs,
      :through => :lmce_disc_users

  # 1:n  (EK_Users)
  has_many  :lmce_bookmarks,
      :class_name => "PlutoMedia::LmceBookmark",
      :foreign_key => "EK_Users"

  # 1:n  (EK_Users_Private)
  has_many  :lmce_users_private,
      :class_name => "PlutoMedia::LmceDisc",
      :foreign_key => "EK_Users_Private"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

