# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.CommandParameter
#
# * primary keys: PK_CommandParameter
# * foreign keys: FK_ParameterType
# * external keys: 
#
# == References
# * PlutoMain::LmceParameterType
#
# == Referenced By
# * PlutoMain::LmceScreenCommandParameter
# * PlutoMain::LmceCommandGroupCommandCommandParameter
# * PlutoMain::LmceCommandCommandParameter
# * PlutoMain::LmceCommandGroupDCommandCommandParameter
#
# == Database Table Columns
#   * PK_CommandParameter    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description            [Type:varchar(30), Default:NULL, Null:NO]
#   * Define                 [Type:varchar(30), Default:NULL, Null:NO]
#   * Comments               [Type:varchar(255), Default:NULL, Null:YES]
#   * FK_ParameterType       [Type:int(11), Default:0, Null:NO]
#   * psc_id                 [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch              [Type:int(11), Default:NULL, Null:YES]
#   * psc_user               [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen             [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict           [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_parameter_type
# * has_many lmce_command_command_parameters
# * has_many lmce_command_group_command_command_parameters
# * has_many lmce_command_group_commands
# * has_many lmce_command_group_d_command_command_parameters
# * has_many lmce_command_group_d_commands
# * has_many lmce_commands
# * has_many lmce_screen_command_parameters
# * has_many lmce_screens
#

class PlutoMain::LmceCommandParameter < PlutoMainDatabase
  set_table_name "CommandParameter"
  set_primary_key "PK_CommandParameter"

  # foreign key references
  # FK_CommandParameter references PlutoMain::LmceParameterType (FK_ParameterType)
  belongs_to  :lmce_parameter_type,
      :class_name => "PlutoMain::LmceParameterType",
      :foreign_key => "FK_ParameterType"

  # n:n via through join table PlutoMain::LmceScreenCommandParameter  (FK_CommandParameter)
  has_many  :lmce_screen_command_parameters,
      :class_name => "PlutoMain::LmceScreenCommandParameter",
      :foreign_key => "FK_CommandParameter"
  has_many  :lmce_screens,
      :through => :lmce_screen_command_parameters

  # n:n via through join table PlutoMain::LmceCommandGroupCommandCommandParameter  (FK_CommandParameter)
  has_many  :lmce_command_group_command_command_parameters,
      :class_name => "PlutoMain::LmceCommandGroupCommandCommandParameter",
      :foreign_key => "FK_CommandParameter"
  has_many  :lmce_command_group_commands,
      :through => :lmce_command_group_command_command_parameters

  # n:n via through join table PlutoMain::LmceCommandCommandParameter  (FK_CommandParameter)
  has_many  :lmce_command_command_parameters,
      :class_name => "PlutoMain::LmceCommandCommandParameter",
      :foreign_key => "FK_CommandParameter"
  has_many  :lmce_commands,
      :through => :lmce_command_command_parameters

  # n:n via through join table PlutoMain::LmceCommandGroupDCommandCommandParameter  (FK_CommandParameter)
  has_many  :lmce_command_group_d_command_command_parameters,
      :class_name => "PlutoMain::LmceCommandGroupDCommandCommandParameter",
      :foreign_key => "FK_CommandParameter"
  has_many  :lmce_command_group_d_commands,
      :through => :lmce_command_group_d_command_command_parameters

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

