# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Package_Directory
# Through Join Table
#
# * primary keys: PK_Package_Directory
# * foreign keys: FK_Package,FK_Directory,FK_OperatingSystem,FK_Distro
# * external keys: 
#
# == References
# * PlutoMain::LmceDistro
# * PlutoMain::LmcePackage
# * PlutoMain::LmceOperatingSystem
# * PlutoMain::LmceDirectory
#
# == Referenced By
# * PlutoMain::LmcePackageDirectoryFile
#
# == Database Table Columns
#   * PK_Package_Directory    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_Package              [Type:int(11), Default:0, Null:NO]
#   * FK_Directory            [Type:int(11), Default:0, Null:NO]
#   * FK_OperatingSystem      [Type:int(11), Default:NULL, Null:YES]
#   * FK_Distro               [Type:int(11), Default:NULL, Null:YES]
#   * Path                    [Type:varchar(255), Default:NULL, Null:NO]
#   * InputPath               [Type:varchar(255), Default:NULL, Null:YES]
#   * FlipSource              [Type:tinyint(1), Default:0, Null:NO]
#   * GenerateDoxygen         [Type:tinyint(4), Default:0, Null:YES]
#   * psc_id                  [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch               [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen              [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                 [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict            [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_directory
# * belongs_to lmce_distro
# * belongs_to lmce_operating_system
# * belongs_to lmce_package
# * has_many lmce_package_directory_files
#

class PlutoMain::LmcePackageDirectory < PlutoMainDatabase
  set_table_name "Package_Directory"
  set_primary_key "PK_Package_Directory"

  # foreign key references
  # FK_Package_Directory references PlutoMain::LmceDistro (FK_Distro)
  belongs_to  :lmce_distro,
      :class_name => "PlutoMain::LmceDistro",
      :foreign_key => "FK_Distro"

  # FK_Package_Directory references PlutoMain::LmcePackage (FK_Package)
  belongs_to  :lmce_package,
      :class_name => "PlutoMain::LmcePackage",
      :foreign_key => "FK_Package"

  # FK_Package_Directory references PlutoMain::LmceOperatingSystem (FK_OperatingSystem)
  belongs_to  :lmce_operating_system,
      :class_name => "PlutoMain::LmceOperatingSystem",
      :foreign_key => "FK_OperatingSystem"

  # FK_Package_Directory references PlutoMain::LmceDirectory (FK_Directory)
  belongs_to  :lmce_directory,
      :class_name => "PlutoMain::LmceDirectory",
      :foreign_key => "FK_Directory"

  # 1:n  (FK_Package_Directory)
  has_many  :lmce_package_directory_files,
      :class_name => "PlutoMain::LmcePackageDirectoryFile",
      :foreign_key => "FK_Package_Directory"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

