# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.EventHandler
#
# * primary keys: PK_EventHandler
# * foreign keys: FK_Event,FK_Criteria,FK_Installation,FK_CommandGroup,FK_CannedEvents,FK_Template
# * external keys: 
#
# == References
# * PlutoMain::LmceEvent
# * PlutoMain::LmceCriteria
# * PlutoMain::LmceTemplate
# * PlutoMain::LmceCommandGroup
# * PlutoMain::LmceCannedEvent
# * PlutoMain::LmceInstallation
#
# == Referenced By
#
# == Database Table Columns
#   * PK_EventHandler    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_Event           [Type:int(11), Default:NULL, Null:YES]
#   * TimedEvent         [Type:int(11), Default:NULL, Null:YES]
#   * Description        [Type:varchar(40), Default:NULL, Null:NO]
#   * FK_Criteria        [Type:int(11), Default:NULL, Null:YES]
#   * FK_Installation    [Type:int(11), Default:NULL, Null:YES]
#   * FK_CommandGroup    [Type:int(11), Default:NULL, Null:YES]
#   * UserCreated        [Type:tinyint(4), Default:0, Null:NO]
#   * FK_CannedEvents    [Type:int(11), Default:NULL, Null:YES]
#   * Disabled           [Type:tinyint(1), Default:0, Null:YES]
#   * FK_Template        [Type:int(11), Default:NULL, Null:YES]
#   * TemplateParm1      [Type:int(11), Default:NULL, Null:YES]
#   * TemplateParm2      [Type:int(11), Default:NULL, Null:YES]
#   * OncePerSeconds     [Type:int(11), Default:NULL, Null:YES]
#   * psc_id             [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch          [Type:int(11), Default:NULL, Null:YES]
#   * psc_user           [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen         [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod            [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict       [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_canned_event
# * belongs_to lmce_command_group
# * belongs_to lmce_criteria
# * belongs_to lmce_event
# * belongs_to lmce_installation
# * belongs_to lmce_template
#

class PlutoMain::LmceEventHandler < PlutoMainDatabase
  set_table_name "EventHandler"
  set_primary_key "PK_EventHandler"

  # foreign key references
  # FK_EventHandler references PlutoMain::LmceEvent (FK_Event)
  belongs_to  :lmce_event,
      :class_name => "PlutoMain::LmceEvent",
      :foreign_key => "FK_Event"

  # FK_EventHandler references PlutoMain::LmceCriteria (FK_Criteria)
  belongs_to  :lmce_criteria,
      :class_name => "PlutoMain::LmceCriteria",
      :foreign_key => "FK_Criteria"

  # FK_EventHandler references PlutoMain::LmceTemplate (FK_Template)
  belongs_to  :lmce_template,
      :class_name => "PlutoMain::LmceTemplate",
      :foreign_key => "FK_Template"

  # FK_EventHandler references PlutoMain::LmceCommandGroup (FK_CommandGroup)
  belongs_to  :lmce_command_group,
      :class_name => "PlutoMain::LmceCommandGroup",
      :foreign_key => "FK_CommandGroup"

  # FK_EventHandler references PlutoMain::LmceCannedEvent (FK_CannedEvents)
  belongs_to  :lmce_canned_event,
      :class_name => "PlutoMain::LmceCannedEvent",
      :foreign_key => "FK_CannedEvents"

  # FK_EventHandler references PlutoMain::LmceInstallation (FK_Installation)
  belongs_to  :lmce_installation,
      :class_name => "PlutoMain::LmceInstallation",
      :foreign_key => "FK_Installation"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

