# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.EntertainArea
#
# * primary keys: PK_EntertainArea
# * foreign keys: FK_Room,FK_FloorplanObjectType
# * external keys: 
#
# == References
# * PlutoMain::LmceFloorplanObjectType
# * PlutoMain::LmceRoom
#
# == Referenced By
# * PlutoMain::LmceCommandGroupEntertainArea
# * PlutoMain::LmceDeviceEntertainArea
#
# == Database Table Columns
#   * PK_EntertainArea          [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_Room                   [Type:int(11), Default:0, Null:NO]
#   * Only1Stream               [Type:tinyint(1), Default:0, Null:NO]
#   * Description               [Type:varchar(50), Default:NULL, Null:NO]
#   * Private                   [Type:tinyint(2), Default:0, Null:NO]
#   * FK_FloorplanObjectType    [Type:int(11), Default:NULL, Null:YES]
#   * FloorplanInfo             [Type:text, Default:NULL, Null:YES]
#   * psc_id                    [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                 [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                  [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                   [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict              [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_floorplan_object_type
# * belongs_to lmce_room
# * has_many lmce_command_group_entertain_areas
# * has_many lmce_command_groups
# * has_many lmce_device_entertain_areas
# * has_many lmce_devices
#

class PlutoMain::LmceEntertainArea < PlutoMainDatabase
  set_table_name "EntertainArea"
  set_primary_key "PK_EntertainArea"

  # foreign key references
  # FK_EntertainArea references PlutoMain::LmceFloorplanObjectType (FK_FloorplanObjectType)
  belongs_to  :lmce_floorplan_object_type,
      :class_name => "PlutoMain::LmceFloorplanObjectType",
      :foreign_key => "FK_FloorplanObjectType"

  # FK_EntertainArea references PlutoMain::LmceRoom (FK_Room)
  belongs_to  :lmce_room,
      :class_name => "PlutoMain::LmceRoom",
      :foreign_key => "FK_Room"

  # n:n via through join table PlutoMain::LmceCommandGroupEntertainArea  (FK_EntertainArea)
  has_many  :lmce_command_group_entertain_areas,
      :class_name => "PlutoMain::LmceCommandGroupEntertainArea",
      :foreign_key => "FK_EntertainArea"
  has_many  :lmce_command_groups,
      :through => :lmce_command_group_entertain_areas

  # n:n via through join table PlutoMain::LmceDeviceEntertainArea  (FK_EntertainArea)
  has_many  :lmce_device_entertain_areas,
      :class_name => "PlutoMain::LmceDeviceEntertainArea",
      :foreign_key => "FK_EntertainArea"
  has_many  :lmce_devices,
      :through => :lmce_device_entertain_areas

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

