# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Package_Source_Compat
#
# * primary keys: PK_Package_Source_Compat
# * foreign keys: FK_Package_Source,FK_OperatingSystem,FK_Distro
# * external keys: 
#
# == References
# * PlutoMain::LmceOperatingSystem
# * PlutoMain::LmceDistro
# * PlutoMain::LmcePackageSource
#
# == Referenced By
#
# == Database Table Columns
#   * PK_Package_Source_Compat    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_Package_Source           [Type:int(11), Default:0, Null:NO]
#   * FK_OperatingSystem          [Type:int(11), Default:NULL, Null:YES]
#   * FK_Distro                   [Type:int(11), Default:NULL, Null:YES]
#   * MustBuildFromSource         [Type:tinyint(1), Default:0, Null:YES]
#   * Comments                    [Type:tinytext, Default:NULL, Null:YES]
#   * psc_id                      [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                   [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                    [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                  [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                     [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_distro
# * belongs_to lmce_operating_system
# * belongs_to lmce_package_source
#

class PlutoMain::LmcePackageSourceCompat < PlutoMainDatabase
  set_table_name "Package_Source_Compat"
  set_primary_key "PK_Package_Source_Compat"

  # foreign key references
  # FK_Package_Source_Compat references PlutoMain::LmceOperatingSystem (FK_OperatingSystem)
  belongs_to  :lmce_operating_system,
      :class_name => "PlutoMain::LmceOperatingSystem",
      :foreign_key => "FK_OperatingSystem"

  # FK_Package_Source_Compat references PlutoMain::LmceDistro (FK_Distro)
  belongs_to  :lmce_distro,
      :class_name => "PlutoMain::LmceDistro",
      :foreign_key => "FK_Distro"

  # FK_Package_Source_Compat references PlutoMain::LmcePackageSource (FK_Package_Source)
  belongs_to  :lmce_package_source,
      :class_name => "PlutoMain::LmcePackageSource",
      :foreign_key => "FK_Package_Source"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

