# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Document_Comment
#
# * primary keys: PK_Document_Comment
# * foreign keys: FK_Document,FK_Users
# * external keys: 
#
# == References
# * PlutoMain::LmceDocument
# * PlutoMain::LmceUser
#
# == Referenced By
#
# == Database Table Columns
#   * PK_Document_Comment    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Document            [Type:int(11), Default:0, Null:NO]
#   * FK_Users               [Type:int(11), Default:0, Null:NO]
#   * Comment                [Type:mediumtext, Default:NULL, Null:NO]
#   * Date                   [Type:datetime, Default:0000-00-00, Null:NO]
#   * psc_id                 [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch              [Type:int(11), Default:NULL, Null:YES]
#   * psc_user               [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen             [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict           [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_document
# * belongs_to lmce_user
#

class PlutoMain::LmceDocumentComment < PlutoMainDatabase
  set_table_name "Document_Comment"
  set_primary_key "PK_Document_Comment"

  # foreign key references
  # FK_Document_Comment references PlutoMain::LmceDocument (FK_Document)
  belongs_to  :lmce_document,
      :class_name => "PlutoMain::LmceDocument",
      :foreign_key => "FK_Document"

  # FK_Document_Comment references PlutoMain::LmceUser (FK_Users)
  belongs_to  :lmce_user,
      :class_name => "PlutoMain::LmceUser",
      :foreign_key => "FK_Users"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line
end

