# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.EventParameter
#
# * primary keys: PK_EventParameter
# * foreign keys: FK_ParameterType
# * external keys: 
#
# == References
# * PlutoMain::LmceParameterType
#
# == Referenced By
# * PlutoMain::LmceEventEventParameter
#
# == Database Table Columns
#   * PK_EventParameter    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description          [Type:varchar(25), Default:NULL, Null:NO]
#   * Define               [Type:varchar(25), Default:NULL, Null:NO]
#   * Comments             [Type:varchar(255), Default:NULL, Null:YES]
#   * FK_ParameterType     [Type:int(11), Default:0, Null:NO]
#   * psc_id               [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch            [Type:int(11), Default:NULL, Null:YES]
#   * psc_user             [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod              [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict         [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_parameter_type
# * has_many lmce_event_event_parameters
# * has_many lmce_events
#

class PlutoMain::LmceEventParameter < PlutoMainDatabase
  set_table_name "EventParameter"
  set_primary_key "PK_EventParameter"

  # foreign key references
  # FK_EventParameter references PlutoMain::LmceParameterType (FK_ParameterType)
  belongs_to  :lmce_parameter_type,
      :class_name => "PlutoMain::LmceParameterType",
      :foreign_key => "FK_ParameterType"

  # n:n via through join table PlutoMain::LmceEventEventParameter  (FK_EventParameter)
  has_many  :lmce_event_event_parameters,
      :class_name => "PlutoMain::LmceEventEventParameter",
      :foreign_key => "FK_EventParameter"
  has_many  :lmce_events,
      :through => :lmce_event_event_parameters

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

