# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Device_CommandGroup
# Through Join Table
#
# * primary keys: FK_Device,FK_CommandGroup
# * foreign keys: FK_Device,FK_CommandGroup
# * external keys: 
#
# == References
# * PlutoMain::LmceDevice
# * PlutoMain::LmceCommandGroup
#
# == Referenced By
# * PlutoMain::LmceDeviceTemplateDeviceCommandGroup
# * PlutoMain::LmceDeviceCommandGroupCommand
# * PlutoMain::LmceDeviceCommandGroupDeviceCommandGroupParent
#
# == Database Table Columns
#   * FK_Device          [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_CommandGroup    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * Sort               [Type:int(11), Default:NULL, Null:YES]
#   * psc_id             [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch          [Type:int(11), Default:NULL, Null:YES]
#   * psc_user           [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen         [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod            [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict       [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_command_group
# * belongs_to lmce_device
# * has_many lmce_commands
# * has_many lmce_device_command_group_commands
# * has_many lmce_device_command_group_device_command_group_parents
# * has_many lmce_device_template_device_command_groups
# * has_many lmce_device_templates
#

class PlutoMain::LmceDeviceCommandGroup < PlutoMainDatabase
  set_table_name "Device_CommandGroup"
  set_primary_keys "FK_Device", "FK_CommandGroup"

  # foreign key references
  # FK_Device_CommandGroup references PlutoMain::LmceDevice (FK_Device)
  belongs_to  :lmce_device,
      :class_name => "PlutoMain::LmceDevice",
      :foreign_key => "FK_Device"

  # FK_Device_CommandGroup references PlutoMain::LmceCommandGroup (FK_CommandGroup)
  belongs_to  :lmce_command_group,
      :class_name => "PlutoMain::LmceCommandGroup",
      :foreign_key => "FK_CommandGroup"

  # n:n via through join table PlutoMain::LmceDeviceTemplateDeviceCommandGroup  (FK_DeviceCommandGroup)
  has_many  :lmce_device_template_device_command_groups,
      :class_name => "PlutoMain::LmceDeviceTemplateDeviceCommandGroup",
      :foreign_key => "FK_Device_CommandGroup"
  has_many  :lmce_device_templates,
      :through => :lmce_device_template_device_command_groups

  # n:n via through join table PlutoMain::LmceDeviceCommandGroupCommand  (FK_DeviceCommandGroup)
  has_many  :lmce_device_command_group_commands,
      :class_name => "PlutoMain::LmceDeviceCommandGroupCommand",
      :foreign_key => "FK_Device_CommandGroup"
  has_many  :lmce_commands,
      :through => :lmce_device_command_group_commands

  # n:n via through join table PlutoMain::LmceDeviceCommandGroupDeviceCommandGroupParent  (FK_DeviceCommandGroup)
  has_many  :lmce_device_command_group_device_command_group_parents,
      :class_name => "PlutoMain::LmceDeviceCommandGroupDeviceCommandGroupParent",
      :foreign_key => "FK_Device_CommandGroup"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

