# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.FloorplanObjectType
#
# * primary keys: PK_FloorplanObjectType
# * foreign keys: FK_FloorplanType,FK_DesignObj_Control
# * external keys: 
#
# == References
# * PlutoMain::LmceFloorplanType
#
# == Referenced By
# * PlutoMain::LmceRoom
# * PlutoMain::LmceFloorplanObjectTypeColor
# * PlutoMain::LmceEntertainArea
#
# == Database Table Columns
#   * PK_FloorplanObjectType    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_FloorplanType          [Type:int(11), Default:0, Null:NO]
#   * Description               [Type:varchar(50), Default:NULL, Null:NO]
#   * Define                    [Type:varchar(50), Default:NULL, Null:NO]
#   * Direction                 [Type:varchar(4), Default:NULL, Null:NO]
#   * FK_DesignObj_Control      [Type:int(11), Default:NULL, Null:YES]
#   * Filename                  [Type:varchar(200), Default:NULL, Null:YES]
#   * FillX                     [Type:int(11), Default:0, Null:NO]
#   * FillY                     [Type:int(11), Default:0, Null:NO]
#   * psc_id                    [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                 [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                  [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                   [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict              [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_floorplan_type
# * has_many lmce_entertain_areas
# * has_many lmce_floorplan_object_type_colors
# * has_many lmce_rooms
#

class PlutoMain::LmceFloorplanObjectType < PlutoMainDatabase
  set_table_name "FloorplanObjectType"
  set_primary_key "PK_FloorplanObjectType"

  # foreign key references
  # FK_FloorplanObjectType references PlutoMain::LmceFloorplanType (FK_FloorplanType)
  belongs_to  :lmce_floorplan_type,
      :class_name => "PlutoMain::LmceFloorplanType",
      :foreign_key => "FK_FloorplanType"

  # 1:n  (FK_FloorplanObjectType)
  has_many  :lmce_rooms,
      :class_name => "PlutoMain::LmceRoom",
      :foreign_key => "FK_FloorplanObjectType"

  # 1:n  (FK_FloorplanObjectType)
  has_many  :lmce_floorplan_object_type_colors,
      :class_name => "PlutoMain::LmceFloorplanObjectTypeColor",
      :foreign_key => "FK_FloorplanObjectType"

  # 1:n  (FK_FloorplanObjectType)
  has_many  :lmce_entertain_areas,
      :class_name => "PlutoMain::LmceEntertainArea",
      :foreign_key => "FK_FloorplanObjectType"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

