# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Orbiter_Variable
# Through Join Table
#
# * primary keys: FK_Orbiter,FK_Variable
# * foreign keys: FK_Orbiter,FK_Variable
# * external keys: 
#
# == References
# * PlutoMain::LmceVariable
# * PlutoMain::LmceOrbiter
#
# == Referenced By
#
# == Database Table Columns
#   * FK_Orbiter      [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Variable     [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * Value           [Type:varchar(50), Default:NULL, Null:YES]
#   * psc_id          [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch       [Type:int(11), Default:NULL, Null:YES]
#   * psc_user        [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen      [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod         [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict    [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_orbiter
# * belongs_to lmce_variable
#

class PlutoMain::LmceOrbiterVariable < PlutoMainDatabase
  set_table_name "Orbiter_Variable"
  set_primary_keys "FK_Orbiter", "FK_Variable"

  # foreign key references
  # FK_Orbiter_Variable references PlutoMain::LmceVariable (FK_Variable)
  belongs_to  :lmce_variable,
      :class_name => "PlutoMain::LmceVariable",
      :foreign_key => "FK_Variable"

  # FK_Orbiter_Variable references PlutoMain::LmceOrbiter (FK_Orbiter)
  belongs_to  :lmce_orbiter,
      :class_name => "PlutoMain::LmceOrbiter",
      :foreign_key => "FK_Orbiter"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

