# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Criteria
#
# * primary keys: PK_Criteria
# * foreign keys: FK_CriteriaParmNesting,FK_CriteriaList,FK_Installation
# * external keys: 
#
# == References
# * PlutoMain::LmceCriteriaParmNesting
# * PlutoMain::LmceInstallation
# * PlutoMain::LmceCriteriaList
#
# == Referenced By
# * PlutoMain::LmceEventHandler
#
# == Database Table Columns
#   * PK_Criteria               [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_CriteriaParmNesting    [Type:int(11), Default:0, Null:NO]
#   * FK_CriteriaList           [Type:int(11), Default:0, Null:NO]
#   * FK_Installation           [Type:int(11), Default:0, Null:NO]
#   * Description               [Type:varchar(25), Default:NULL, Null:NO]
#   * Define                    [Type:varchar(25), Default:NULL, Null:NO]
#   * psc_id                    [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                 [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                  [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                   [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict              [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_criteria_list
# * belongs_to lmce_criteria_parm_nesting
# * belongs_to lmce_installation
# * has_many lmce_event_handlers
#

class PlutoMain::LmceCriteria < PlutoMainDatabase
  set_table_name "Criteria"
  set_primary_key "PK_Criteria"

  # foreign key references
  # FK_Criteria references PlutoMain::LmceCriteriaParmNesting (FK_CriteriaParmNesting)
  belongs_to  :lmce_criteria_parm_nesting,
      :class_name => "PlutoMain::LmceCriteriaParmNesting",
      :foreign_key => "FK_CriteriaParmNesting"

  # FK_Criteria references PlutoMain::LmceInstallation (FK_Installation)
  belongs_to  :lmce_installation,
      :class_name => "PlutoMain::LmceInstallation",
      :foreign_key => "FK_Installation"

  # FK_Criteria references PlutoMain::LmceCriteriaList (FK_CriteriaList)
  belongs_to  :lmce_criteria_list,
      :class_name => "PlutoMain::LmceCriteriaList",
      :foreign_key => "FK_CriteriaList"

  # 1:n  (FK_Criteria)
  has_many  :lmce_event_handlers,
      :class_name => "PlutoMain::LmceEventHandler",
      :foreign_key => "FK_Criteria"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

