# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DeviceTemplate_DesignObj
# Through Join Table
#
# * primary keys: FK_DeviceTemplate,FK_DesignObj
# * foreign keys: FK_DeviceTemplate,FK_DesignObj
# * external keys: 
#
# == References
# * PlutoMain::LmceDeviceTemplate
# * PlutoMain::LmceDesignObj
#
# == Referenced By
#
# == Database Table Columns
#   * FK_DeviceTemplate    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_DesignObj         [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * psc_id               [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch            [Type:int(11), Default:NULL, Null:YES]
#   * psc_user             [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod              [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict         [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_design_obj
# * belongs_to lmce_device_template
#

class PlutoMain::LmceDeviceTemplateDesignObj < PlutoMainDatabase
  set_table_name "DeviceTemplate_DesignObj"
  set_primary_keys "FK_DeviceTemplate", "FK_DesignObj"

  # foreign key references
  # FK_DeviceTemplate_DesignObj references PlutoMain::LmceDeviceTemplate (FK_DeviceTemplate)
  belongs_to  :lmce_device_template,
      :class_name => "PlutoMain::LmceDeviceTemplate",
      :foreign_key => "FK_DeviceTemplate"

  # FK_DeviceTemplate_DesignObj references PlutoMain::LmceDesignObj (FK_DesignObj)
  belongs_to  :lmce_design_obj,
      :class_name => "PlutoMain::LmceDesignObj",
      :foreign_key => "FK_DesignObj"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

