# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.CriteriaParmNesting
#
# * primary keys: PK_CriteriaParmNesting
# * foreign keys: FK_CriteriaParmNesting_Parent
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceCriteria
# * PlutoMain::LmceCriteriaParm
#
# == Database Table Columns
#   * PK_CriteriaParmNesting           [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_CriteriaParmNesting_Parent    [Type:int(11), Default:NULL, Null:YES]
#   * IsAnd                            [Type:tinyint(4), Default:0, Null:NO]
#   * IsNot                            [Type:tinyint(4), Default:0, Null:NO]
#   * psc_id                           [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                        [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                         [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                       [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                          [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                     [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to parent
# * has_many criteria_parm_nesting_parents
# * has_many lmce_criteria_parms
# * has_many lmce_criterias
#

class PlutoMain::LmceCriteriaParmNesting < PlutoMainDatabase
  set_table_name "CriteriaParmNesting"
  set_primary_key "PK_CriteriaParmNesting"

  # foreign key references
  # 1:n  (FK_CriteriaParmNesting)
  has_many  :lmce_criterias,
      :class_name => "PlutoMain::LmceCriteria",
      :foreign_key => "FK_CriteriaParmNesting"

  # 1:n  (FK_CriteriaParmNesting)
  has_many  :lmce_criteria_parms,
      :class_name => "PlutoMain::LmceCriteriaParm",
      :foreign_key => "FK_CriteriaParmNesting"

  # self references
  belongs_to  :parent,
      :class_name => "PlutoMain::LmceCriteriaParmNesting",
      :foreign_key => "FK_CriteriaParmNesting_Parent"
  has_many  :criteria_parm_nesting_parents,
      :class_name => "PlutoMain::LmceCriteriaParmNesting",
      :foreign_key => "FK_CriteriaParmNesting_Parent"
  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

