# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Software_Source
#
# * primary keys: PK_Software_Source
# * foreign keys: FK_Software
# * external keys: 
#
# == References
# * PlutoMain::LmceSoftware
#
# == Referenced By
# * PlutoMain::LmceSoftwareDevice
#
# == Database Table Columns
#   * PK_Software_Source      [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_Software             [Type:int(11), Default:0, Null:NO]
#   * Downloadurl             [Type:varchar(255), Default:NULL, Null:YES]
#   * Version                 [Type:varchar(10), Default:NULL, Null:YES]
#   * Distro                  [Type:varchar(20), Default:NULL, Null:YES]
#   * Required_Version_Min    [Type:varchar(11), Default:NULL, Null:YES]
#   * Required_Version_Max    [Type:varchar(11), Default:NULL, Null:YES]
#   * RepositoryName          [Type:varchar(100), Default:NULL, Null:YES]
#   * Iconstr                 [Type:blob, Default:NULL, Null:YES]
#   * Title                   [Type:varchar(20), Default:NULL, Null:YES]
#   * Description             [Type:text, Default:NULL, Null:YES]
#   * HomeURL                 [Type:varchar(100), Default:NULL, Null:YES]
#   * Category                [Type:varchar(20), Default:NULL, Null:YES]
#   * Misc                    [Type:varchar(20), Default:NULL, Null:YES]
#   * Target                  [Type:varchar(20), Default:NULL, Null:YES]
#   * Importance              [Type:varchar(20), Default:NULL, Null:YES]
#   * Rating                  [Type:float(6,2), Default:0.00, Null:NO]
#   * Virus_Free              [Type:tinyint(1), Default:0, Null:NO]
#   * PC_Type                 [Type:char(2), Default:SM, Null:YES]
#   * Sum_md5                 [Type:varchar(33), Default:NULL, Null:YES]
#   * Sum_sha                 [Type:varchar(41), Default:NULL, Null:YES]
#   * psc_id                  [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch               [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen              [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                 [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict            [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_software
# * has_many lmce_software_devices
# * has_many lmce_softwares
#

class PlutoMain::LmceSoftwareSource < PlutoMainDatabase
  set_table_name "Software_Source"
  set_primary_key "PK_Software_Source"

  # foreign key references
  # FK_Software_Source references PlutoMain::LmceSoftware (FK_Software)
  belongs_to  :lmce_software,
      :class_name => "PlutoMain::LmceSoftware",
      :foreign_key => "FK_Software"

  # n:n via through join table PlutoMain::LmceSoftwareDevice  (FK_Software_Source)
  has_many  :lmce_software_devices,
      :class_name => "PlutoMain::LmceSoftwareDevice",
      :foreign_key => "FK_Software_Source"
  has_many  :lmce_softwares,
      :through => :lmce_software_devices

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

