# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DeviceTemplate_DeviceCategory_ControlledVia
# Through Join Table
#
# * primary keys: PK_DeviceTemplate_DeviceCategory_ControlledVia
# * foreign keys: FK_DeviceTemplate,FK_DeviceCategory
# * external keys: 
#
# == References
# * PlutoMain::LmceDeviceTemplate
# * PlutoMain::LmceDeviceCategory
#
# == Referenced By
# * PlutoMain::LmceDeviceTemplateDeviceCategoryControlledViaPipe
#
# == Database Table Columns
#   * PK_DeviceTemplate_DeviceCategory_ControlledVia    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_DeviceTemplate                                 [Type:int(11), Default:0, Null:NO]
#   * FK_DeviceCategory                                 [Type:int(11), Default:0, Null:NO]
#   * Description                                       [Type:varchar(25), Default:NULL, Null:YES]
#   * RerouteMessagesToParent                           [Type:tinyint(4), Default:0, Null:NO]
#   * AutoCreateChildren                                [Type:tinyint(4), Default:0, Null:NO]
#   * psc_id                                            [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                                         [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                                          [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                                        [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                                           [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                                      [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device_category
# * belongs_to lmce_device_template
# * has_many lmce_device_template_device_category_controlled_via_pipes
# * has_many lmce_pipes
#

class PlutoMain::LmceDeviceTemplateDeviceCategoryControlledVia < PlutoMainDatabase
  set_table_name "DeviceTemplate_DeviceCategory_ControlledVia"
  set_primary_key "PK_DeviceTemplate_DeviceCategory_ControlledVia"

  # foreign key references
  # FK_DeviceTemplate_DeviceCategory_ControlledVia references PlutoMain::LmceDeviceTemplate (FK_DeviceTemplate)
  belongs_to  :lmce_device_template,
      :class_name => "PlutoMain::LmceDeviceTemplate",
      :foreign_key => "FK_DeviceTemplate"

  # FK_DeviceTemplate_DeviceCategory_ControlledVia references PlutoMain::LmceDeviceCategory (FK_DeviceCategory)
  belongs_to  :lmce_device_category,
      :class_name => "PlutoMain::LmceDeviceCategory",
      :foreign_key => "FK_DeviceCategory"

  # n:n via through join table PlutoMain::LmceDeviceTemplateDeviceCategoryControlledViaPipe  (FK_DeviceTemplate_DeviceCategory_ControlledVia)
  has_many  :lmce_device_template_device_category_controlled_via_pipes,
      :class_name => "PlutoMain::LmceDeviceTemplateDeviceCategoryControlledViaPipe",
      :foreign_key => "FK_DeviceTemplate_DeviceCategory_ControlledVia"
  has_many  :lmce_pipes,
      :through => :lmce_device_template_device_category_controlled_via_pipes

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

