# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.RepositoryType
#
# * primary keys: PK_RepositoryType
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceRepositorySource
#
# == Database Table Columns
#   * PK_RepositoryType    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description          [Type:varchar(30), Default:NULL, Null:NO]
#   * Define               [Type:varchar(25), Default:NULL, Null:YES]
#   * SourceOnly           [Type:tinyint(1), Default:NULL, Null:YES]
#   * PathToFile           [Type:varchar(50), Default:NULL, Null:YES]
#   * Instructions         [Type:tinytext, Default:NULL, Null:YES]
#   * psc_id               [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch            [Type:int(11), Default:NULL, Null:YES]
#   * psc_user             [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod              [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict         [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_repository_sources
#

class PlutoMain::LmceRepositoryType < PlutoMainDatabase
  set_table_name "RepositoryType"
  set_primary_key "PK_RepositoryType"

  # foreign key references
  # 1:n  (FK_RepositoryType)
  has_many  :lmce_repository_sources,
      :class_name => "PlutoMain::LmceRepositorySource",
      :foreign_key => "FK_RepositoryType"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

