# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.City
#
# * primary keys: PK_City
# * foreign keys: FK_Country,FK_Region,FK_TimeZone
# * external keys: 
#
# == References
# * PlutoMain::LmceRegion
# * PlutoMain::LmceCountry
# * PlutoMain::LmceTimeZone
#
# == Referenced By
# * PlutoMain::LmceInstallation
# * PlutoMain::LmcePostalCode
#
# == Database Table Columns
#   * PK_City        [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_Country     [Type:int(11), Default:0, Null:NO]
#   * FK_Region      [Type:int(11), Default:NULL, Null:YES]
#   * City           [Type:varchar(45), Default:NULL, Null:YES]
#   * Latitude       [Type:float, Default:NULL, Null:YES]
#   * Longitude      [Type:float, Default:NULL, Null:YES]
#   * DmaId          [Type:smallint(6), Default:NULL, Null:YES]
#   * County         [Type:varchar(25), Default:NULL, Null:YES]
#   * Code           [Type:varchar(4), Default:NULL, Null:YES]
#   * FK_TimeZone    [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_country
# * belongs_to lmce_region
# * belongs_to lmce_time_zone
# * has_many lmce_installations
# * has_many lmce_postal_codes
#

class PlutoMain::LmceCity < PlutoMainDatabase
  set_table_name "City"
  set_primary_key "PK_City"

  # foreign key references
  # FK_City references PlutoMain::LmceRegion (FK_Region)
  belongs_to  :lmce_region,
      :class_name => "PlutoMain::LmceRegion",
      :foreign_key => "FK_Region"

  # FK_City references PlutoMain::LmceCountry (FK_Country)
  belongs_to  :lmce_country,
      :class_name => "PlutoMain::LmceCountry",
      :foreign_key => "FK_Country"

  # FK_City references PlutoMain::LmceTimeZone (FK_TimeZone)
  belongs_to  :lmce_time_zone,
      :class_name => "PlutoMain::LmceTimeZone",
      :foreign_key => "FK_TimeZone"

  # 1:n  (FK_City)
  has_many  :lmce_installations,
      :class_name => "PlutoMain::LmceInstallation",
      :foreign_key => "FK_City"

  # 1:n  (FK_City)
  has_many  :lmce_postal_codes,
      :class_name => "PlutoMain::LmcePostalCode",
      :foreign_key => "FK_City"


  # add your model extensions after this line

end

