# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DHCPDevice_DeviceData
# Through Join Table
#
# * primary keys: FK_DHCPDevice,FK_DeviceData
# * foreign keys: FK_DHCPDevice,FK_DeviceData
# * external keys: 
#
# == References
# * PlutoMain::LmceDhcpDevice
# * PlutoMain::LmceDeviceData
#
# == Referenced By
#
# == Database Table Columns
#   * FK_DHCPDevice    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_DeviceData    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * IK_DeviceData    [Type:text, Default:NULL, Null:YES]
#   * psc_id           [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch        [Type:int(11), Default:NULL, Null:YES]
#   * psc_user         [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen       [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod          [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict     [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device_data
# * belongs_to lmce_dhcp_device
#

class PlutoMain::LmceDhcpDeviceDeviceData < PlutoMainDatabase
  set_table_name "DHCPDevice_DeviceData"
  set_primary_keys "FK_DHCPDevice", "FK_DeviceData"

  # foreign key references
  # FK_DHCPDevice_DeviceData references PlutoMain::LmceDhcpDevice (FK_DHCPDevice)
  belongs_to  :lmce_dhcp_device,
      :class_name => "PlutoMain::LmceDhcpDevice",
      :foreign_key => "FK_DHCPDevice"

  # FK_DHCPDevice_DeviceData references PlutoMain::LmceDeviceData (FK_DeviceData)
  belongs_to  :lmce_device_data,
      :class_name => "PlutoMain::LmceDeviceData",
      :foreign_key => "FK_DeviceData"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

