# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.PaidLicense
#
# * primary keys: PK_PaidLicense
# * foreign keys: FK_Device,FK_Package,FK_License
# * external keys: 
#
# == References
# * PlutoMain::LmceDevice
# * PlutoMain::LmcePackage
# * PlutoMain::LmceLicense
#
# == Referenced By
#
# == Database Table Columns
#   * PK_PaidLicense       [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_Device            [Type:int(11), Default:NULL, Null:YES]
#   * UseWithoutLicense    [Type:tinyint(1), Default:NULL, Null:YES]
#   * ValidUntil           [Type:datetime, Default:NULL, Null:YES]
#   * FK_Package           [Type:int(11), Default:NULL, Null:YES]
#   * FK_License           [Type:int(11), Default:NULL, Null:YES]
#   * ReferenceNumber      [Type:varchar(25), Default:NULL, Null:YES]
#   * Username             [Type:varchar(25), Default:NULL, Null:YES]
#   * Password             [Type:varchar(25), Default:NULL, Null:YES]
#   * Key                  [Type:text, Default:NULL, Null:YES]
#   * psc_id               [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch            [Type:int(11), Default:NULL, Null:YES]
#   * psc_user             [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod              [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict         [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device
# * belongs_to lmce_license
# * belongs_to lmce_package
#

class PlutoMain::LmcePaidLicense < PlutoMainDatabase
  set_table_name "PaidLicense"
  set_primary_key "PK_PaidLicense"

  # foreign key references
  # FK_PaidLicense references PlutoMain::LmceDevice (FK_Device)
  belongs_to  :lmce_device,
      :class_name => "PlutoMain::LmceDevice",
      :foreign_key => "FK_Device"

  # FK_PaidLicense references PlutoMain::LmcePackage (FK_Package)
  belongs_to  :lmce_package,
      :class_name => "PlutoMain::LmcePackage",
      :foreign_key => "FK_Package"

  # FK_PaidLicense references PlutoMain::LmceLicense (FK_License)
  belongs_to  :lmce_license,
      :class_name => "PlutoMain::LmceLicense",
      :foreign_key => "FK_License"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

