# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DeviceCategory
#
# * primary keys: PK_DeviceCategory
# * foreign keys: FK_DeviceCategory_Parent
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceDeviceCategoryEvent
# * PlutoMain::LmceDhcpDevice
# * PlutoMain::LmceDeviceTemplate
# * PlutoMain::LmceCommandGroupDCommand
# * PlutoMain::LmceConfigType
# * PlutoMain::LmceDeviceCategoryDeviceData
# * PlutoMain::LmceDeviceTemplateDeviceCategoryControlledVia
# * PlutoMain::LmceInfraredGroup
#
# == Database Table Columns
#   * PK_DeviceCategory           [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_DeviceCategory_Parent    [Type:int(11), Default:NULL, Null:YES]
#   * Description                 [Type:varchar(30), Default:NULL, Null:YES]
#   * Define                      [Type:varchar(20), Default:NULL, Null:YES]
#   * IsAV                        [Type:tinyint(4), Default:0, Null:NO]
#   * psc_id                      [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                   [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                    [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                  [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                     [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to parent
# * has_many device_category_parents
# * has_many lmce_command_group_d_commands
# * has_many lmce_command_group_ds
# * has_many lmce_config_types
# * has_many lmce_device_category_device_datas
# * has_many lmce_device_category_events
# * has_many lmce_device_datas
# * has_many lmce_device_template_device_category_controlled_vias
# * has_many lmce_device_templates
# * has_many lmce_device_templates
# * has_many lmce_dhcp_devices
# * has_many lmce_events
# * has_many lmce_infrared_groups
#

class PlutoMain::LmceDeviceCategory < PlutoMainDatabase
  set_table_name "DeviceCategory"
  set_primary_key "PK_DeviceCategory"

  # foreign key references
  # n:n via through join table PlutoMain::LmceDeviceCategoryEvent  (FK_DeviceCategory)
  has_many  :lmce_device_category_events,
      :class_name => "PlutoMain::LmceDeviceCategoryEvent",
      :foreign_key => "FK_DeviceCategory"
  has_many  :lmce_events,
      :through => :lmce_device_category_events

  # 1:n  (FK_DeviceCategory)
  has_many  :lmce_dhcp_devices,
      :class_name => "PlutoMain::LmceDhcpDevice",
      :foreign_key => "FK_DeviceCategory"

  # 1:n  (FK_DeviceCategory)
  has_many  :lmce_device_templates,
      :class_name => "PlutoMain::LmceDeviceTemplate",
      :foreign_key => "FK_DeviceCategory"

  # n:n via through join table PlutoMain::LmceCommandGroupDCommand  (FK_DeviceCategory)
  has_many  :lmce_command_group_d_commands,
      :class_name => "PlutoMain::LmceCommandGroupDCommand",
      :foreign_key => "FK_DeviceCategory"
  has_many  :lmce_command_group_ds,
      :through => :lmce_command_group_d_commands

  # 1:n  (FK_DeviceCategory)
  has_many  :lmce_config_types,
      :class_name => "PlutoMain::LmceConfigType",
      :foreign_key => "FK_DeviceCategory"

  # n:n via through join table PlutoMain::LmceDeviceCategoryDeviceData  (FK_DeviceCategory)
  has_many  :lmce_device_category_device_datas,
      :class_name => "PlutoMain::LmceDeviceCategoryDeviceData",
      :foreign_key => "FK_DeviceCategory"
  has_many  :lmce_device_datas,
      :through => :lmce_device_category_device_datas

  # n:n via through join table PlutoMain::LmceDeviceTemplateDeviceCategoryControlledVia  (FK_DeviceCategory)
  has_many  :lmce_device_template_device_category_controlled_vias,
      :class_name => "PlutoMain::LmceDeviceTemplateDeviceCategoryControlledVia",
      :foreign_key => "FK_DeviceCategory"
  has_many  :lmce_device_templates,
      :through => :lmce_device_template_device_category_controlled_vias

  # 1:n  (FK_DeviceCategory)
  has_many  :lmce_infrared_groups,
      :class_name => "PlutoMain::LmceInfraredGroup",
      :foreign_key => "FK_DeviceCategory"

  # self references
  belongs_to  :parent,
      :class_name => "PlutoMain::LmceDeviceCategory",
      :foreign_key => "FK_DeviceCategory_Parent"
  has_many  :device_category_parents,
      :class_name => "PlutoMain::LmceDeviceCategory",
      :foreign_key => "FK_DeviceCategory_Parent"
  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

