# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Variable
#
# * primary keys: PK_Variable
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceOrbiterVariable
#
# == Database Table Columns
#   * PK_Variable     [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description     [Type:varchar(25), Default:NULL, Null:NO]
#   * Define          [Type:varchar(25), Default:NULL, Null:NO]
#   * Comments        [Type:mediumtext, Default:NULL, Null:YES]
#   * psc_id          [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch       [Type:int(11), Default:NULL, Null:YES]
#   * psc_user        [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen      [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod         [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict    [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_orbiter_variables
# * has_many lmce_orbiters
#

class PlutoMain::LmceVariable < PlutoMainDatabase
  set_table_name "Variable"
  set_primary_key "PK_Variable"

  # foreign key references
  # n:n via through join table PlutoMain::LmceOrbiterVariable  (FK_Variable)
  has_many  :lmce_orbiter_variables,
      :class_name => "PlutoMain::LmceOrbiterVariable",
      :foreign_key => "FK_Variable"
  has_many  :lmce_orbiters,
      :through => :lmce_orbiter_variables

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

