# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.PnpQueue
#
# * primary keys: PK_PnpQueue
# * foreign keys: FK_CommMethod,FK_PnpProtocol,FK_DeviceTemplate,FK_Device_Created,FK_Device_Reported
# * external keys: 
#
# == References
# * PlutoMain::LmceCommMethod
# * PlutoMain::LmcePnpProtocol
# * PlutoMain::LmceDeviceTemplate
#
# == Referenced By
#
# == Database Table Columns
#   * PK_PnpQueue           [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * DetectedDate          [Type:datetime, Default:NULL, Null:YES]
#   * VendorModelId         [Type:varchar(60), Default:NULL, Null:YES]
#   * Path                  [Type:varchar(60), Default:NULL, Null:YES]
#   * IPaddress             [Type:varchar(15), Default:NULL, Null:YES]
#   * MACaddress            [Type:varchar(17), Default:NULL, Null:YES]
#   * Category              [Type:varchar(100), Default:NULL, Null:YES]
#   * SerialNumber          [Type:varchar(255), Default:NULL, Null:YES]
#   * FK_CommMethod         [Type:int(11), Default:NULL, Null:YES]
#   * FK_PnpProtocol        [Type:int(11), Default:NULL, Null:YES]
#   * FK_DeviceTemplate     [Type:int(11), Default:NULL, Null:YES]
#   * FK_Device_Created     [Type:int(11), Default:NULL, Null:YES]
#   * FK_Device_Reported    [Type:int(11), Default:NULL, Null:YES]
#   * Signature             [Type:varchar(20), Default:NULL, Null:YES]
#   * Removed               [Type:int(11), Default:NULL, Null:YES]
#   * Stage                 [Type:tinyint(3), Default:NULL, Null:YES]
#   * Processed             [Type:tinyint(1), Default:NULL, Null:YES]
#   * Parms                 [Type:varchar(255), Default:NULL, Null:YES]
#   * Description           [Type:char(255), Default:NULL, Null:YES]
#   * psc_id                [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch             [Type:int(11), Default:NULL, Null:YES]
#   * psc_user              [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen            [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod               [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict          [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_comm_method
# * belongs_to lmce_device_template
# * belongs_to lmce_pnp_protocol
#

class PlutoMain::LmcePnpQueue < PlutoMainDatabase
  set_table_name "PnpQueue"
  set_primary_key "PK_PnpQueue"

  # foreign key references
  # FK_PnpQueue references PlutoMain::LmceCommMethod (FK_CommMethod)
  belongs_to  :lmce_comm_method,
      :class_name => "PlutoMain::LmceCommMethod",
      :foreign_key => "FK_CommMethod"

  # FK_PnpQueue references PlutoMain::LmcePnpProtocol (FK_PnpProtocol)
  belongs_to  :lmce_pnp_protocol,
      :class_name => "PlutoMain::LmcePnpProtocol",
      :foreign_key => "FK_PnpProtocol"

  # FK_PnpQueue references PlutoMain::LmceDeviceTemplate (FK_DeviceTemplate)
  belongs_to  :lmce_device_template,
      :class_name => "PlutoMain::LmceDeviceTemplate",
      :foreign_key => "FK_DeviceTemplate"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

