# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.MediaType_DesignObj
#
# * primary keys: PK_MediaType_DesignObj
# * foreign keys: FK_MediaType,FK_Screen,FK_DesignObj_Popup,FK_Screen_FileList,FK_Screen_OSD,FK_Screen_Alt,FK_Screen_Alt_OSD,FK_Screen_OSD_Speed,FK_Screen_OSD_Track,FK_Skin
# * external keys: 
#
# == References
# * PlutoMain::LmceScreen
# * PlutoMain::LmceSkin
# * PlutoMain::LmceMediaType
#
# == Referenced By
# * PlutoMain::LmceRemoteControl
#
# == Database Table Columns
#   * PK_MediaType_DesignObj    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_MediaType              [Type:int(11), Default:0, Null:NO]
#   * FK_Screen                 [Type:int(11), Default:0, Null:NO]
#   * FK_DesignObj_Popup        [Type:int(11), Default:NULL, Null:YES]
#   * FK_Screen_FileList        [Type:int(11), Default:NULL, Null:YES]
#   * FK_Screen_OSD             [Type:int(11), Default:NULL, Null:YES]
#   * FK_Screen_Alt             [Type:int(11), Default:NULL, Null:YES]
#   * FK_Screen_Alt_OSD         [Type:int(11), Default:NULL, Null:YES]
#   * FK_Screen_OSD_Speed       [Type:int(11), Default:NULL, Null:YES]
#   * FK_Screen_OSD_Track       [Type:int(11), Default:NULL, Null:YES]
#   * Description               [Type:varchar(50), Default:NULL, Null:YES]
#   * FK_Skin                   [Type:int(11), Default:NULL, Null:YES]
#   * UIVersion                 [Type:int(11), Default:NULL, Null:YES]
#   * psc_id                    [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch                 [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                  [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                   [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict              [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_media_type
# * belongs_to lmce_screen
# * belongs_to lmce_skin
# * has_many lmce_remote_controls
#

class PlutoMain::LmceMediaTypeDesignObj < PlutoMainDatabase
  set_table_name "MediaType_DesignObj"
  set_primary_key "PK_MediaType_DesignObj"

  # foreign key references
  # FK_MediaType_DesignObj references PlutoMain::LmceScreen (FK_Screen)
  belongs_to  :lmce_screen,
      :class_name => "PlutoMain::LmceScreen",
      :foreign_key => "FK_Screen"

  # FK_MediaType_DesignObj references PlutoMain::LmceSkin (FK_Skin)
  belongs_to  :lmce_skin,
      :class_name => "PlutoMain::LmceSkin",
      :foreign_key => "FK_Skin"

  # FK_MediaType_DesignObj references PlutoMain::LmceMediaType (FK_MediaType)
  belongs_to  :lmce_media_type,
      :class_name => "PlutoMain::LmceMediaType",
      :foreign_key => "FK_MediaType"

  # 1:n  (FK_MediaType_DesignObj)
  has_many  :lmce_remote_controls,
      :class_name => "PlutoMain::LmceRemoteControl",
      :foreign_key => "FK_MediaType_DesignObj"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

