# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.CachedScreens
#
# * primary keys: FK_Orbiter,FK_DesignObj,Version
# * foreign keys: FK_Orbiter,FK_DesignObj
# * external keys: 
#
# == References
# * PlutoMain::LmceDesignObj
# * PlutoMain::LmceOrbiter
#
# == Referenced By
#
# == Database Table Columns
#   * FK_Orbiter              [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_DesignObj            [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * Version                 [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * Modification_LastGen    [Type:datetime, Default:0000-00-00, Null:NO]
#   * ContainsArrays          [Type:tinyint(4), Default:0, Null:YES]
#   * Schema                  [Type:int(11), Default:1, Null:YES]
#   * psc_id                  [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch               [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen              [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                 [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict            [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_design_obj
# * belongs_to lmce_orbiter
#

class PlutoMain::LmceCachedScreen < PlutoMainDatabase
  set_table_name "CachedScreens"
  set_primary_keys "FK_Orbiter", "FK_DesignObj", "Version"

  # foreign key references
  # FK_CachedScreens references PlutoMain::LmceDesignObj (FK_DesignObj)
  belongs_to  :lmce_design_obj,
      :class_name => "PlutoMain::LmceDesignObj",
      :foreign_key => "FK_DesignObj"

  # FK_CachedScreens references PlutoMain::LmceOrbiter (FK_Orbiter)
  belongs_to  :lmce_orbiter,
      :class_name => "PlutoMain::LmceOrbiter",
      :foreign_key => "FK_Orbiter"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

