# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Text
#
# * primary keys: PK_Text
# * foreign keys: FK_TextCategory
# * external keys: 
#
# == References
# * PlutoMain::LmceTextCategory
#
# == Referenced By
# * PlutoMain::LmceTextL
# * PlutoMain::LmceDesignObjVariationText
# * PlutoMain::LmceTextLsAltVersion
#
# == Database Table Columns
#   * PK_Text            [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_TextCategory    [Type:int(11), Default:0, Null:NO]
#   * Description        [Type:varchar(40), Default:NULL, Null:NO]
#   * Define             [Type:varchar(40), Default:NULL, Null:NO]
#   * AddToOrbiter       [Type:tinyint(1), Default:0, Null:YES]
#   * psc_id             [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch          [Type:int(11), Default:NULL, Null:YES]
#   * psc_user           [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen         [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod            [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict       [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_text_category
# * has_many lmce_design_obj_variation_texts
# * has_many lmce_design_obj_variations
# * has_one lmce_text_l
# * has_one lmce_text_ls_alt_version
#

class PlutoMain::LmceText < PlutoMainDatabase
  set_table_name "Text"
  set_primary_key "PK_Text"

  # foreign key references
  # FK_Text references PlutoMain::LmceTextCategory (FK_TextCategory)
  belongs_to  :lmce_text_category,
      :class_name => "PlutoMain::LmceTextCategory",
      :foreign_key => "FK_TextCategory"

  # 1:1  (FK_Text)
  has_one  :lmce_text_l,
      :class_name => "PlutoMain::LmceTextL",
      :foreign_key => "FK_Text"

  # n:n via through join table PlutoMain::LmceDesignObjVariationText  (FK_Text)
  has_many  :lmce_design_obj_variation_texts,
      :class_name => "PlutoMain::LmceDesignObjVariationText",
      :foreign_key => "FK_Text"
  has_many  :lmce_design_obj_variations,
      :through => :lmce_design_obj_variation_texts

  # 1:1  (FK_Text)
  has_one  :lmce_text_ls_alt_version,
      :class_name => "PlutoMain::LmceTextLsAltVersion",
      :foreign_key => "FK_Text"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

