# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Style
#
# * primary keys: PK_Style
# * foreign keys: FK_Style_Selected,FK_Style_Highlighted,FK_Style_Alt
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceStyleVariation
# * PlutoMain::LmceSkin
# * PlutoMain::LmceDesignObjVariationTextSkinLanguage
#
# == Database Table Columns
#   * PK_Style                  [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description               [Type:varchar(20), Default:NULL, Null:YES]
#   * FK_Style_Selected         [Type:int(11), Default:NULL, Null:YES]
#   * FK_Style_Highlighted      [Type:int(11), Default:NULL, Null:YES]
#   * FK_Style_Alt              [Type:int(11), Default:NULL, Null:YES]
#   * AlwaysIncludeOnOrbiter    [Type:tinyint(4), Default:0, Null:NO]
#   * psc_id                    [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                 [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                  [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                   [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict              [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to alt
# * belongs_to highlighted
# * belongs_to selected
# * has_many lmce_design_obj_variation_text_skin_languages
# * has_many lmce_skins
# * has_many lmce_style_variations
# * has_many style_alts
# * has_many style_highlighteds
# * has_many style_selecteds
#

class PlutoMain::LmceStyle < PlutoMainDatabase
  set_table_name "Style"
  set_primary_key "PK_Style"

  # foreign key references
  # 1:n  (FK_Style)
  has_many  :lmce_style_variations,
      :class_name => "PlutoMain::LmceStyleVariation",
      :foreign_key => "FK_Style"

  # 1:n  (FK_Style)
  has_many  :lmce_skins,
      :class_name => "PlutoMain::LmceSkin",
      :foreign_key => "FK_Style"

  # 1:n  (FK_Style)
  has_many  :lmce_design_obj_variation_text_skin_languages,
      :class_name => "PlutoMain::LmceDesignObjVariationTextSkinLanguage",
      :foreign_key => "FK_Style"

  # self references
  belongs_to  :selected,
      :class_name => "PlutoMain::LmceStyle",
      :foreign_key => "FK_Style_Selected"
  has_many  :style_selecteds,
      :class_name => "PlutoMain::LmceStyle",
      :foreign_key => "FK_Style_Selected"
  belongs_to  :highlighted,
      :class_name => "PlutoMain::LmceStyle",
      :foreign_key => "FK_Style_Highlighted"
  has_many  :style_highlighteds,
      :class_name => "PlutoMain::LmceStyle",
      :foreign_key => "FK_Style_Highlighted"
  belongs_to  :alt,
      :class_name => "PlutoMain::LmceStyle",
      :foreign_key => "FK_Style_Alt"
  has_many  :style_alts,
      :class_name => "PlutoMain::LmceStyle",
      :foreign_key => "FK_Style_Alt"
  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

