# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.InfraredGroup_Command_Preferred
#
# * primary keys: FK_InfraredGroup_Command,FK_Installation
# * foreign keys: FK_InfraredGroup_Command,FK_Installation
# * external keys: 
#
# == References
# * PlutoMain::LmceInfraredGroupCommand
# * PlutoMain::LmceInstallation
#
# == Referenced By
#
# == Database Table Columns
#   * FK_InfraredGroup_Command    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Installation             [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * psc_id                      [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                   [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                    [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                  [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                     [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_infrared_group_command
# * belongs_to lmce_installation
#

class PlutoMain::LmceInfraredGroupCommandPreferred < PlutoMainDatabase
  set_table_name "InfraredGroup_Command_Preferred"
  set_primary_keys "FK_InfraredGroup_Command", "FK_Installation"

  # foreign key references
  # FK_InfraredGroup_Command_Preferred references PlutoMain::LmceInfraredGroupCommand (FK_InfraredGroup_Command)
  belongs_to  :lmce_infrared_group_command,
      :class_name => "PlutoMain::LmceInfraredGroupCommand",
      :foreign_key => "FK_InfraredGroup_Command"

  # FK_InfraredGroup_Command_Preferred references PlutoMain::LmceInstallation (FK_Installation)
  belongs_to  :lmce_installation,
      :class_name => "PlutoMain::LmceInstallation",
      :foreign_key => "FK_Installation"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

