# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.PostalCode
#
# * primary keys: PK_PostalCode
# * foreign keys: FK_City,FK_Country
# * external keys: 
#
# == References
# * PlutoMain::LmceCountry
# * PlutoMain::LmceCity
#
# == Referenced By
# * PlutoMain::LmceInstallation
#
# == Database Table Columns
#   * PK_PostalCode    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * PostalCode       [Type:varchar(10), Null:NO]
#   * Long             [Type:varchar(10), Null:NO]
#   * Lat              [Type:varchar(10), Default:NULL, Null:YES]
#   * City             [Type:varchar(60), Default:NULL, Null:YES]
#   * State            [Type:char(2), Default:NULL, Null:YES]
#   * County           [Type:varchar(60), Default:NULL, Null:YES]
#   * FK_City          [Type:int(11), Default:NULL, Null:YES]
#   * FK_Country       [Type:int(11), Default:0, Null:NO]
#
# == Associations
# * belongs_to lmce_city
# * belongs_to lmce_country
# * has_many lmce_installations
# * has_many lmce_postal_code_providers
# * has_many lmce_providers
#

require 'pluto_myth/lmce_postal_code_provider'

include PlutoMyth

class PlutoMain::LmcePostalCode < PlutoMainDatabase
  set_table_name "PostalCode"
  set_primary_key "PK_PostalCode"

  # foreign key references
  # FK_PostalCode references PlutoMain::LmceCountry (FK_Country)
  belongs_to  :lmce_country,
      :class_name => "PlutoMain::LmceCountry",
      :foreign_key => "FK_Country"

  # FK_PostalCode references PlutoMain::LmceCity (FK_City)
  belongs_to  :lmce_city,
      :class_name => "PlutoMain::LmceCity",
      :foreign_key => "FK_City"

  # 1:n  (FK_PostalCode)
  has_many  :lmce_installations,
      :class_name => "PlutoMain::LmceInstallation",
      :foreign_key => "FK_PostalCode"

  # external key references
  # n:n via through join table PlutoMyth::LmcePostalCodeProvider  (EK_PostalCode)
  has_many  :lmce_postal_code_providers,
      :class_name => "PlutoMyth::LmcePostalCodeProvider",
      :foreign_key => "EK_PostalCode"
  has_many  :lmce_providers,
      :through => :lmce_postal_code_providers


  # add your model extensions after this line

end

