# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Package_Source
#
# * primary keys: PK_Package_Source
# * foreign keys: FK_Package,FK_RepositorySource
# * external keys: 
#
# == References
# * PlutoMain::LmceRepositorySource
# * PlutoMain::LmcePackage
#
# == Referenced By
# * PlutoMain::LmcePackageSourceCompat
#
# == Database Table Columns
#   * PK_Package_Source      [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_Package             [Type:int(11), Default:0, Null:NO]
#   * Name                   [Type:varchar(255), Default:NULL, Null:YES]
#   * FK_RepositorySource    [Type:int(11), Default:0, Null:NO]
#   * Repository             [Type:text, Default:NULL, Null:YES]
#   * Version                [Type:varchar(30), Default:NULL, Null:YES]
#   * Parms                  [Type:varchar(30), Default:NULL, Null:YES]
#   * Replaces               [Type:varchar(255), Default:NULL, Null:YES]
#   * Conflicts              [Type:varchar(255), Default:NULL, Null:YES]
#   * Provides               [Type:varchar(255), Default:NULL, Null:YES]
#   * psc_id                 [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch              [Type:int(11), Default:NULL, Null:YES]
#   * psc_user               [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen             [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict           [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_package
# * belongs_to lmce_repository_source
# * has_many lmce_package_source_compats
#

class PlutoMain::LmcePackageSource < PlutoMainDatabase
  set_table_name "Package_Source"
  set_primary_key "PK_Package_Source"

  # foreign key references
  # FK_Package_Source references PlutoMain::LmceRepositorySource (FK_RepositorySource)
  belongs_to  :lmce_repository_source,
      :class_name => "PlutoMain::LmceRepositorySource",
      :foreign_key => "FK_RepositorySource"

  # FK_Package_Source references PlutoMain::LmcePackage (FK_Package)
  belongs_to  :lmce_package,
      :class_name => "PlutoMain::LmcePackage",
      :foreign_key => "FK_Package"

  # 1:n  (FK_Package_Source)
  has_many  :lmce_package_source_compats,
      :class_name => "PlutoMain::LmcePackageSourceCompat",
      :foreign_key => "FK_Package_Source"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

