# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.InstallWizard_Distro
# Through Join Table
#
# * primary keys: PK_InstallWizard_Distro
# * foreign keys: FK_InstallWizard,FK_OperatingSystem,FK_Distro
# * external keys: 
#
# == References
# * PlutoMain::LmceDistro
# * PlutoMain::LmceInstallWizard
# * PlutoMain::LmceOperatingSystem
#
# == Referenced By
#
# == Database Table Columns
#   * PK_InstallWizard_Distro    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_InstallWizard           [Type:int(11), Default:NULL, Null:YES]
#   * FK_OperatingSystem         [Type:int(11), Default:NULL, Null:YES]
#   * FK_Distro                  [Type:int(11), Default:NULL, Null:YES]
#   * Comments                   [Type:mediumtext, Default:NULL, Null:NO]
#   * psc_id                     [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                  [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                   [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                 [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                    [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict               [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_distro
# * belongs_to lmce_install_wizard
# * belongs_to lmce_operating_system
#

class PlutoMain::LmceInstallWizardDistro < PlutoMainDatabase
  set_table_name "InstallWizard_Distro"
  set_primary_key "PK_InstallWizard_Distro"

  # foreign key references
  # FK_InstallWizard_Distro references PlutoMain::LmceDistro (FK_Distro)
  belongs_to  :lmce_distro,
      :class_name => "PlutoMain::LmceDistro",
      :foreign_key => "FK_Distro"

  # FK_InstallWizard_Distro references PlutoMain::LmceInstallWizard (FK_InstallWizard)
  belongs_to  :lmce_install_wizard,
      :class_name => "PlutoMain::LmceInstallWizard",
      :foreign_key => "FK_InstallWizard"

  # FK_InstallWizard_Distro references PlutoMain::LmceOperatingSystem (FK_OperatingSystem)
  belongs_to  :lmce_operating_system,
      :class_name => "PlutoMain::LmceOperatingSystem",
      :foreign_key => "FK_OperatingSystem"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

