# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Button
#
# * primary keys: PK_Button
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceDesignObjVariation
# * PlutoMain::LmceDesignObjVariationZone
#
# == Database Table Columns
#   * PK_Button       [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description     [Type:varchar(25), Default:NULL, Null:NO]
#   * Define          [Type:varchar(25), Default:NULL, Null:NO]
#   * psc_id          [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch       [Type:int(11), Default:NULL, Null:YES]
#   * psc_user        [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen      [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod         [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict    [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_design_obj_variation_zones
# * has_many lmce_design_obj_variations
#

class PlutoMain::LmceButton < PlutoMainDatabase
  set_table_name "Button"
  set_primary_key "PK_Button"

  # foreign key references
  # 1:n  (FK_Button)
  has_many  :lmce_design_obj_variations,
      :class_name => "PlutoMain::LmceDesignObjVariation",
      :foreign_key => "FK_Button"

  # 1:n  (FK_Button)
  has_many  :lmce_design_obj_variation_zones,
      :class_name => "PlutoMain::LmceDesignObjVariationZone",
      :foreign_key => "FK_Button"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

