# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Software_Device
# Through Join Table
#
# * primary keys: FK_Software,FK_Device
# * foreign keys: FK_Software,FK_Device,FK_Software_Source
# * external keys: 
#
# == References
# * PlutoMain::LmceSoftwareSource
# * PlutoMain::LmceSoftware
# * PlutoMain::LmceDevice
#
# == Referenced By
#
# == Database Table Columns
#   * FK_Software           [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Device             [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Software_Source    [Type:int(11), Default:NULL, Null:YES]
#   * Status                [Type:char(1), Default:N, Null:YES]
#   * psc_id                [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch             [Type:int(11), Default:NULL, Null:YES]
#   * psc_user              [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen            [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod               [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict          [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device
# * belongs_to lmce_software
# * belongs_to lmce_software_source
# * belongs_to source
# * has_many software_sources
#

class PlutoMain::LmceSoftwareDevice < PlutoMainDatabase
  set_table_name "Software_Device"
  set_primary_keys "FK_Software", "FK_Device"

  # foreign key references
  # FK_Software_Device references PlutoMain::LmceSoftwareSource (FK_Software_Source)
  belongs_to  :lmce_software_source,
      :class_name => "PlutoMain::LmceSoftwareSource",
      :foreign_key => "FK_Software_Source"

  # FK_Software_Device references PlutoMain::LmceSoftware (FK_Software)
  belongs_to  :lmce_software,
      :class_name => "PlutoMain::LmceSoftware",
      :foreign_key => "FK_Software"

  # FK_Software_Device references PlutoMain::LmceDevice (FK_Device)
  belongs_to  :lmce_device,
      :class_name => "PlutoMain::LmceDevice",
      :foreign_key => "FK_Device"

  # self references
  belongs_to  :source,
      :class_name => "PlutoMain::LmceSoftwareDevice",
      :foreign_key => "FK_Software_Source"
  has_many  :software_sources,
      :class_name => "PlutoMain::LmceSoftwareDevice",
      :foreign_key => "FK_Software_Source"
  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

