# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.UnknownDevices
#
# * primary keys: PK_UnknownDevices
# * foreign keys: FK_Device_PC
# * external keys: 
#
# == References
#
# == Referenced By
#
# == Database Table Columns
#   * PK_UnknownDevices    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description          [Type:varchar(30), Default:NULL, Null:YES]
#   * MacAddress           [Type:varchar(17), Default:NULL, Null:YES]
#   * IPAddress            [Type:varchar(15), Default:NULL, Null:YES]
#   * VendorModelId        [Type:varchar(60), Default:NULL, Null:YES]
#   * SerialNumber         [Type:varchar(255), Default:NULL, Null:YES]
#   * FK_Device_PC         [Type:int(11), Default:NULL, Null:YES]
#   * psc_id               [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch            [Type:int(11), Default:NULL, Null:YES]
#   * psc_user             [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod              [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict         [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
#

class PlutoMain::LmceUnknownDevice < PlutoMainDatabase
  set_table_name "UnknownDevices"
  set_primary_key "PK_UnknownDevices"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

