# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.EffectType
#
# * primary keys: PK_EffectType
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceEffectTypeEffectSkin
#
# == Database Table Columns
#   * PK_EffectType    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description      [Type:varchar(30), Default:NULL, Null:NO]
#   * Define           [Type:varchar(20), Default:NULL, Null:YES]
#   * psc_id           [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch        [Type:int(11), Default:NULL, Null:YES]
#   * psc_user         [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen       [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod          [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict     [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_effect_type_effect_skins
# * has_many lmce_effects
#

class PlutoMain::LmceEffectType < PlutoMainDatabase
  set_table_name "EffectType"
  set_primary_key "PK_EffectType"

  # foreign key references
  # n:n via through join table PlutoMain::LmceEffectTypeEffectSkin  (FK_EffectType)
  has_many  :lmce_effect_type_effect_skins,
      :class_name => "PlutoMain::LmceEffectTypeEffectSkin",
      :foreign_key => "FK_EffectType"
  has_many  :lmce_effects,
      :through => :lmce_effect_type_effect_skins

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

