# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.ConfigType_Setting
#
# * primary keys: PK_ConfigType_Setting
# * foreign keys: FK_ConfigType
# * external keys: 
#
# == References
# * PlutoMain::LmceConfigType
#
# == Referenced By
# * PlutoMain::LmceConfigTypeToken
#
# == Database Table Columns
#   * PK_ConfigType_Setting    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_ConfigType            [Type:int(11), Default:0, Null:NO]
#   * Description              [Type:text, Default:NULL, Null:NO]
#   * psc_id                   [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                 [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen               [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                  [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict             [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_config_type
# * has_one lmce_config_type_token
#

class PlutoMain::LmceConfigTypeSetting < PlutoMainDatabase
  set_table_name "ConfigType_Setting"
  set_primary_key "PK_ConfigType_Setting"

  # foreign key references
  # FK_ConfigType_Setting references PlutoMain::LmceConfigType (FK_ConfigType)
  belongs_to  :lmce_config_type,
      :class_name => "PlutoMain::LmceConfigType",
      :foreign_key => "FK_ConfigType"

  # 1:1  (FK_ConfigType_Setting)
  has_one  :lmce_config_type_token,
      :class_name => "PlutoMain::LmceConfigTypeToken",
      :foreign_key => "FK_ConfigType_Setting"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

