# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Orbiter
#
# * primary keys: PK_Orbiter
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceRoomUser
# * PlutoMain::LmceRemoteControl
# * PlutoMain::LmceDeviceOrbiter
# * PlutoMain::LmceCachedScreen
# * PlutoMain::LmceOrbiterVariable
# * PlutoMain::LmceOrbiterUsersPasswordReq
#
# == Database Table Columns
#   * PK_Orbiter              [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FloorplanInfo           [Type:mediumtext, Default:NULL, Null:YES]
#   * Modification_LastGen    [Type:datetime, Default:NULL, Null:YES]
#   * Regen                   [Type:tinyint(1), Default:1, Null:YES]
#   * Size                    [Type:varchar(50), Default:NULL, Null:YES]
#   * RegenInProgress         [Type:tinyint(1), Default:0, Null:YES]
#   * RegenStatus             [Type:varchar(50), Default:NULL, Null:YES]
#   * RegenPercent            [Type:int(11), Default:NULL, Null:YES]
#   * ScenariosFloorplans     [Type:varchar(255), Default:NULL, Null:YES]
#   * FirstRegen              [Type:tinyint(1), Default:NULL, Null:YES]
#   * psc_id                  [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch               [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen              [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                 [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict            [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_cached_screens
# * has_many lmce_device_orbiters
# * has_many lmce_devices
# * has_many lmce_orbiter_users_password_reqs
# * has_many lmce_orbiter_variables
# * has_many lmce_remote_controls
# * has_many lmce_room_users
# * has_many lmce_rooms
# * has_many lmce_users
# * has_many lmce_variables
#

class PlutoMain::LmceOrbiter < PlutoMainDatabase
  set_table_name "Orbiter"
  set_primary_key "PK_Orbiter"

  # foreign key references
  # n:n via through join table PlutoMain::LmceRoomUser  (FK_Orbiter)
  has_many  :lmce_room_users,
      :class_name => "PlutoMain::LmceRoomUser",
      :foreign_key => "FK_Orbiter"
  has_many  :lmce_rooms,
      :through => :lmce_room_users

  # 1:n  (FK_Orbiter)
  has_many  :lmce_remote_controls,
      :class_name => "PlutoMain::LmceRemoteControl",
      :foreign_key => "FK_Orbiter"

  # n:n via through join table PlutoMain::LmceDeviceOrbiter  (FK_Orbiter)
  has_many  :lmce_device_orbiters,
      :class_name => "PlutoMain::LmceDeviceOrbiter",
      :foreign_key => "FK_Orbiter"
  has_many  :lmce_devices,
      :through => :lmce_device_orbiters

  # 1:n  (FK_Orbiter)
  has_many  :lmce_cached_screens,
      :class_name => "PlutoMain::LmceCachedScreen",
      :foreign_key => "FK_Orbiter"

  # n:n via through join table PlutoMain::LmceOrbiterVariable  (FK_Orbiter)
  has_many  :lmce_orbiter_variables,
      :class_name => "PlutoMain::LmceOrbiterVariable",
      :foreign_key => "FK_Orbiter"
  has_many  :lmce_variables,
      :through => :lmce_orbiter_variables

  # n:n via through join table PlutoMain::LmceOrbiterUsersPasswordReq  (FK_Orbiter)
  has_many  :lmce_orbiter_users_password_reqs,
      :class_name => "PlutoMain::LmceOrbiterUsersPasswordReq",
      :foreign_key => "FK_Orbiter"
  has_many  :lmce_users,
      :through => :lmce_orbiter_users_password_reqs

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

