# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Installation
#
# * primary keys: PK_Installation
# * foreign keys: FK_Country,FK_City,FK_PostalCode,FK_Version,FK_RepositoryType_Source,FK_RepositoryType_Binaries
# * external keys: 
#
# == References
# * PlutoMain::LmceVersion
# * PlutoMain::LmceCountry
# * PlutoMain::LmcePostalCode
# * PlutoMain::LmceCity
#
# == Referenced By
# * PlutoMain::LmceDeviceGroup
# * PlutoMain::LmceInfraredGroupCommandPreferred
# * PlutoMain::LmceInstallationUser
# * PlutoMain::LmceInstallationRepositorySourceUrl
# * PlutoMain::LmceSetupStep
# * PlutoMain::LmceHouseholdInstallation
# * PlutoMain::LmceRoom
# * PlutoMain::LmceCriteria
# * PlutoMain::LmceCommandGroup
# * PlutoMain::LmceEventHandler
# * PlutoMain::LmceDevice
# * PlutoMain::LmceFloorplan
#
# == Database Table Columns
#   * PK_Installation               [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description                   [Type:varchar(20), Default:NULL, Null:NO]
#   * Name                          [Type:varchar(30), Default:NULL, Null:YES]
#   * Address                       [Type:varchar(50), Default:NULL, Null:YES]
#   * City                          [Type:varchar(20), Default:NULL, Null:YES]
#   * State                         [Type:varchar(10), Default:NULL, Null:YES]
#   * Zip                           [Type:varchar(10), Default:NULL, Null:YES]
#   * FK_Country                    [Type:int(11), Default:NULL, Null:YES]
#   * FK_City                       [Type:int(11), Default:NULL, Null:YES]
#   * FK_PostalCode                 [Type:int(11), Default:NULL, Null:YES]
#   * ActivationCode                [Type:varchar(50), Default:NULL, Null:YES]
#   * LastStatus                    [Type:text, Default:NULL, Null:YES]
#   * LastAlive                     [Type:datetime, Default:NULL, Null:YES]
#   * isActive                      [Type:tinyint(4), Default:0, Null:NO]
#   * FK_Version                    [Type:int(11), Default:NULL, Null:YES]
#   * isMonitored                   [Type:tinyint(4), Default:NULL, Null:YES]
#   * FK_RepositoryType_Source      [Type:int(11), Default:4, Null:YES]
#   * FK_RepositoryType_Binaries    [Type:int(11), Default:1, Null:YES]
#   * psc_id                        [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                     [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                      [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                    [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                       [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                  [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_city
# * belongs_to lmce_country
# * belongs_to lmce_postal_code
# * belongs_to lmce_version
# * has_many lmce_command_groups
# * has_many lmce_criterias
# * has_many lmce_device_groups
# * has_many lmce_devices
# * has_many lmce_event_handlers
# * has_many lmce_floorplans
# * has_many lmce_household_installations
# * has_many lmce_households
# * has_many lmce_infrared_group_command_preferreds
# * has_many lmce_installation_repository_source_urls
# * has_many lmce_installation_users
# * has_many lmce_repository_source_urls
# * has_many lmce_rooms
# * has_many lmce_setup_steps
# * has_many lmce_users
#

class PlutoMain::LmceInstallation < PlutoMainDatabase
  set_table_name "Installation"
  set_primary_key "PK_Installation"

  # foreign key references
  # FK_Installation references PlutoMain::LmceVersion (FK_Version)
  belongs_to  :lmce_version,
      :class_name => "PlutoMain::LmceVersion",
      :foreign_key => "FK_Version"

  # FK_Installation references PlutoMain::LmceCountry (FK_Country)
  belongs_to  :lmce_country,
      :class_name => "PlutoMain::LmceCountry",
      :foreign_key => "FK_Country"

  # FK_Installation references PlutoMain::LmcePostalCode (FK_PostalCode)
  belongs_to  :lmce_postal_code,
      :class_name => "PlutoMain::LmcePostalCode",
      :foreign_key => "FK_PostalCode"

  # FK_Installation references PlutoMain::LmceCity (FK_City)
  belongs_to  :lmce_city,
      :class_name => "PlutoMain::LmceCity",
      :foreign_key => "FK_City"

  # 1:n  (FK_Installation)
  has_many  :lmce_device_groups,
      :class_name => "PlutoMain::LmceDeviceGroup",
      :foreign_key => "FK_Installation"

  # 1:n  (FK_Installation)
  has_many  :lmce_infrared_group_command_preferreds,
      :class_name => "PlutoMain::LmceInfraredGroupCommandPreferred",
      :foreign_key => "FK_Installation"

  # n:n via through join table PlutoMain::LmceInstallationUser  (FK_Installation)
  has_many  :lmce_installation_users,
      :class_name => "PlutoMain::LmceInstallationUser",
      :foreign_key => "FK_Installation"
  has_many  :lmce_users,
      :through => :lmce_installation_users

  # n:n via through join table PlutoMain::LmceInstallationRepositorySourceUrl  (FK_Installation)
  has_many  :lmce_installation_repository_source_urls,
      :class_name => "PlutoMain::LmceInstallationRepositorySourceUrl",
      :foreign_key => "FK_Installation"
  has_many  :lmce_repository_source_urls,
      :through => :lmce_installation_repository_source_urls

  # 1:n  (FK_Installation)
  has_many  :lmce_setup_steps,
      :class_name => "PlutoMain::LmceSetupStep",
      :foreign_key => "FK_Installation"

  # n:n via through join table PlutoMain::LmceHouseholdInstallation  (FK_Installation)
  has_many  :lmce_household_installations,
      :class_name => "PlutoMain::LmceHouseholdInstallation",
      :foreign_key => "FK_Installation"
  has_many  :lmce_households,
      :through => :lmce_household_installations

  # 1:n  (FK_Installation)
  has_many  :lmce_rooms,
      :class_name => "PlutoMain::LmceRoom",
      :foreign_key => "FK_Installation"

  # 1:n  (FK_Installation)
  has_many  :lmce_criterias,
      :class_name => "PlutoMain::LmceCriteria",
      :foreign_key => "FK_Installation"

  # 1:n  (FK_Installation)
  has_many  :lmce_command_groups,
      :class_name => "PlutoMain::LmceCommandGroup",
      :foreign_key => "FK_Installation"

  # 1:n  (FK_Installation)
  has_many  :lmce_event_handlers,
      :class_name => "PlutoMain::LmceEventHandler",
      :foreign_key => "FK_Installation"

  # 1:n  (FK_Installation)
  has_many  :lmce_devices,
      :class_name => "PlutoMain::LmceDevice",
      :foreign_key => "FK_Installation"

  # 1:n  (FK_Installation)
  has_many  :lmce_floorplans,
      :class_name => "PlutoMain::LmceFloorplan",
      :foreign_key => "FK_Installation"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

