# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Language
#
# * primary keys: PK_Language
# * foreign keys: FK_Language_TextPlacement
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceTextLsAltVersion
# * PlutoMain::LmceUser
# * PlutoMain::LmceDesignObjVariationDesignObjParameter
# * PlutoMain::LmceTextL
# * PlutoMain::LmceDesignObjVariationTextSkinLanguage
# * PlutoMain::LmceDesignObjVariationDesignObjSkinLanguage
#
# == Database Table Columns
#   * PK_Language                  [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description                  [Type:varchar(30), Default:NULL, Null:NO]
#   * FK_Language_TextPlacement    [Type:int(11), Default:NULL, Null:YES]
#   * psc_id                       [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                    [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                     [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                   [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                      [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                 [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to text_placement
# * has_many language_text_placements
# * has_many lmce_design_obj_variation_design_obj_parameters
# * has_many lmce_design_obj_variation_design_obj_skin_languages
# * has_many lmce_design_obj_variation_text_skin_languages
# * has_many lmce_design_obj_variations
# * has_many lmce_users
# * has_one lmce_text_l
# * has_one lmce_text_ls_alt_version
#

class PlutoMain::LmceLanguage < PlutoMainDatabase
  set_table_name "Language"
  set_primary_key "PK_Language"

  # foreign key references
  # 1:1  (FK_Language)
  has_one  :lmce_text_ls_alt_version,
      :class_name => "PlutoMain::LmceTextLsAltVersion",
      :foreign_key => "FK_Language"

  # 1:n  (FK_Language)
  has_many  :lmce_users,
      :class_name => "PlutoMain::LmceUser",
      :foreign_key => "FK_Language"

  # n:n via through join table PlutoMain::LmceDesignObjVariationDesignObjParameter  (FK_Language)
  has_many  :lmce_design_obj_variation_design_obj_parameters,
      :class_name => "PlutoMain::LmceDesignObjVariationDesignObjParameter",
      :foreign_key => "FK_Language"
  has_many  :lmce_design_obj_variations,
      :through => :lmce_design_obj_variation_design_obj_parameters

  # 1:1  (FK_Language)
  has_one  :lmce_text_l,
      :class_name => "PlutoMain::LmceTextL",
      :foreign_key => "FK_Language"

  # 1:n  (FK_Language)
  has_many  :lmce_design_obj_variation_text_skin_languages,
      :class_name => "PlutoMain::LmceDesignObjVariationTextSkinLanguage",
      :foreign_key => "FK_Language"

  # 1:n  (FK_Language)
  has_many  :lmce_design_obj_variation_design_obj_skin_languages,
      :class_name => "PlutoMain::LmceDesignObjVariationDesignObjSkinLanguage",
      :foreign_key => "FK_Language"

  # self references
  belongs_to  :text_placement,
      :class_name => "PlutoMain::LmceLanguage",
      :foreign_key => "FK_Language_TextPlacement"
  has_many  :language_text_placements,
      :class_name => "PlutoMain::LmceLanguage",
      :foreign_key => "FK_Language_TextPlacement"
  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

