# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Household
#
# * primary keys: PK_Household
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceHouseholdInstallation
#
# == Database Table Columns
#   * PK_Household    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * psc_id          [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch       [Type:int(11), Default:NULL, Null:YES]
#   * psc_user        [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen      [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod         [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict    [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_household_installations
# * has_many lmce_installations
#

class PlutoMain::LmceHousehold < PlutoMainDatabase
  set_table_name "Household"
  set_primary_key "PK_Household"

  # foreign key references
  # n:n via through join table PlutoMain::LmceHouseholdInstallation  (FK_Household)
  has_many  :lmce_household_installations,
      :class_name => "PlutoMain::LmceHouseholdInstallation",
      :foreign_key => "FK_Household"
  has_many  :lmce_installations,
      :through => :lmce_household_installations

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

