# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Installation_RepositorySource_URL
# Through Join Table
#
# * primary keys: FK_Installation,FK_RepositorySource_URL
# * foreign keys: FK_Installation,FK_RepositorySource_URL
# * external keys: 
#
# == References
# * PlutoMain::LmceRepositorySourceUrl
# * PlutoMain::LmceInstallation
#
# == Referenced By
#
# == Database Table Columns
#   * FK_Installation            [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_RepositorySource_URL    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * psc_id                     [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                  [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                   [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                 [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                    [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict               [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_installation
# * belongs_to lmce_repository_source_url
#

class PlutoMain::LmceInstallationRepositorySourceUrl < PlutoMainDatabase
  set_table_name "Installation_RepositorySource_URL"
  set_primary_keys "FK_Installation", "FK_RepositorySource_URL"

  # foreign key references
  # FK_Installation_RepositorySource_URL references PlutoMain::LmceRepositorySourceUrl (FK_RepositorySource_URL)
  belongs_to  :lmce_repository_source_url,
      :class_name => "PlutoMain::LmceRepositorySourceUrl",
      :foreign_key => "FK_RepositorySource_URL"

  # FK_Installation_RepositorySource_URL references PlutoMain::LmceInstallation (FK_Installation)
  belongs_to  :lmce_installation,
      :class_name => "PlutoMain::LmceInstallation",
      :foreign_key => "FK_Installation"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

