# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DeviceTemplate_DeviceCategory_ControlledVia_Pipe
# Through Join Table
#
# * primary keys: FK_DeviceTemplate_DeviceCategory_ControlledVia,FK_Pipe
# * foreign keys: FK_DeviceTemplate_DeviceCategory_ControlledVia,FK_Pipe,FK_Command_Input,FK_Command_Output
# * external keys: 
#
# == References
# * PlutoMain::LmceDeviceTemplateDeviceCategoryControlledVia
# * PlutoMain::LmcePipe
#
# == Referenced By
#
# == Database Table Columns
#   * FK_DeviceTemplate_DeviceCategory_ControlledVia    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Pipe                                           [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Command_Input                                  [Type:int(11), Default:NULL, Null:YES]
#   * FK_Command_Output                                 [Type:int(11), Default:NULL, Null:YES]
#   * ToChild                                           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_id                                            [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                                         [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                                          [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                                        [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                                           [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                                      [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device_template_device_category_controlled_via
# * belongs_to lmce_pipe
#

class PlutoMain::LmceDeviceTemplateDeviceCategoryControlledViaPipe < PlutoMainDatabase
  set_table_name "DeviceTemplate_DeviceCategory_ControlledVia_Pipe"
  set_primary_keys "FK_DeviceTemplate_DeviceCategory_ControlledVia", "FK_Pipe"

  # foreign key references
  # FK_DeviceTemplate_DeviceCategory_ControlledVia_Pipe references PlutoMain::LmceDeviceTemplateDeviceCategoryControlledVia (FK_DeviceTemplate_DeviceCategory_ControlledVia)
  belongs_to  :lmce_device_template_device_category_controlled_via,
      :class_name => "PlutoMain::LmceDeviceTemplateDeviceCategoryControlledVia",
      :foreign_key => "FK_DeviceTemplate_DeviceCategory_ControlledVia"

  # FK_DeviceTemplate_DeviceCategory_ControlledVia_Pipe references PlutoMain::LmcePipe (FK_Pipe)
  belongs_to  :lmce_pipe,
      :class_name => "PlutoMain::LmcePipe",
      :foreign_key => "FK_Pipe"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

