# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.ParameterType
#
# * primary keys: PK_ParameterType
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceEventParameter
# * PlutoMain::LmceDeviceData
# * PlutoMain::LmceCriteriaParmList
# * PlutoMain::LmceCommandParameter
# * PlutoMain::LmceDesignObjParameter
#
# == Database Table Columns
#   * PK_ParameterType    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description         [Type:varchar(20), Default:NULL, Null:NO]
#   * Define              [Type:varchar(15), Default:NULL, Null:NO]
#   * CPPType             [Type:varchar(10), Default:NULL, Null:YES]
#   * psc_id              [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch           [Type:int(11), Default:NULL, Null:YES]
#   * psc_user            [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen          [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod             [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict        [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_command_parameters
# * has_many lmce_criteria_parm_lists
# * has_many lmce_design_obj_parameters
# * has_many lmce_device_datas
# * has_many lmce_event_parameters
#

class PlutoMain::LmceParameterType < PlutoMainDatabase
  set_table_name "ParameterType"
  set_primary_key "PK_ParameterType"

  # foreign key references
  # 1:n  (FK_ParameterType)
  has_many  :lmce_event_parameters,
      :class_name => "PlutoMain::LmceEventParameter",
      :foreign_key => "FK_ParameterType"

  # 1:n  (FK_ParameterType)
  has_many  :lmce_device_datas,
      :class_name => "PlutoMain::LmceDeviceData",
      :foreign_key => "FK_ParameterType"

  # 1:n  (FK_ParameterType)
  has_many  :lmce_criteria_parm_lists,
      :class_name => "PlutoMain::LmceCriteriaParmList",
      :foreign_key => "FK_ParameterType"

  # 1:n  (FK_ParameterType)
  has_many  :lmce_command_parameters,
      :class_name => "PlutoMain::LmceCommandParameter",
      :foreign_key => "FK_ParameterType"

  # 1:n  (FK_ParameterType)
  has_many  :lmce_design_obj_parameters,
      :class_name => "PlutoMain::LmceDesignObjParameter",
      :foreign_key => "FK_ParameterType"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

