# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DeviceTemplate
#
# * primary keys: PK_DeviceTemplate
# * foreign keys: FK_DeviceCategory,FK_Manufacturer,FK_StabilityStatus,FK_Package,FK_Users_Maintainer,FK_OperatingSystem,FK_Distro,FK_Licensing,FK_InfraredGroup,FK_CommMethod,FK_PnpLevel
# * external keys: 
#
# == References
# * PlutoMain::LmcePnpLevel
# * PlutoMain::LmceManufacturer
# * PlutoMain::LmceLicensing
# * PlutoMain::LmceDeviceCategory
# * PlutoMain::LmcePackage
# * PlutoMain::LmceDistro
# * PlutoMain::LmceInfraredGroup
# * PlutoMain::LmceStabilityStatus
# * PlutoMain::LmceCommMethod
# * PlutoMain::LmceOperatingSystem
#
# == Referenced By
# * PlutoMain::LmceDeviceTemplateAv
# * PlutoMain::LmceScreenDesignObj
# * PlutoMain::LmceDeviceTemplateDeviceData
# * PlutoMain::LmceInfraredGroupCommand
# * PlutoMain::LmceInstallWizard
# * PlutoMain::LmceDeviceTemplateInfraredGroup
# * PlutoMain::LmceDeviceTemplateEvent
# * PlutoMain::LmceDeviceTemplateDeviceCommandGroup
# * PlutoMain::LmceDhcpDevice
# * PlutoMain::LmceDeviceTemplateDeviceTemplateControlledVia
# * PlutoMain::LmceDevice
# * PlutoMain::LmcePnpQueue
# * PlutoMain::LmceDeviceTemplateDspMode
# * PlutoMain::LmceDeviceTemplatePageSetup
# * PlutoMain::LmceDeviceTemplateDeviceTemplateRelated
# * PlutoMain::LmceDeviceTemplateOutput
# * PlutoMain::LmceCommandGroupDCommand
# * PlutoMain::LmceConfigType
# * PlutoMain::LmceDeviceTemplateDeviceCategoryControlledVia
# * PlutoMain::LmceDeviceTemplateMediaType
# * PlutoMain::LmceDeviceTemplateDesignObj
# * PlutoMain::LmceDeviceTemplateInput
# * PlutoMain::LmceStartupScript
#
# == Database Table Columns
#   * PK_DeviceTemplate      [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description            [Type:varchar(30), Default:NULL, Null:NO]
#   * Comments               [Type:longtext, Default:NULL, Null:YES]
#   * FK_DeviceCategory      [Type:int(11), Default:0, Null:NO]
#   * FK_Manufacturer        [Type:int(11), Default:NULL, Null:YES]
#   * Define                 [Type:varchar(30), Default:NULL, Null:NO]
#   * ImplementsDCE          [Type:tinyint(4), Default:0, Null:NO]
#   * IsEmbedded             [Type:tinyint(1), Default:0, Null:YES]
#   * CommandLine            [Type:varchar(100), Default:NULL, Null:YES]
#   * IsPlugAndPlay          [Type:tinyint(4), Default:0, Null:NO]
#   * IsIPBased              [Type:tinyint(4), Default:0, Null:NO]
#   * IsPlugIn               [Type:tinyint(4), Default:0, Null:NO]
#   * IRFrequency            [Type:int(11), Default:NULL, Null:YES]
#   * FK_StabilityStatus     [Type:int(11), Default:NULL, Null:YES]
#   * FK_Package             [Type:int(11), Default:NULL, Null:YES]
#   * DestinationDir         [Type:varchar(50), Default:NULL, Null:YES]
#   * FK_Users_Maintainer    [Type:int(11), Default:1, Null:NO]
#   * FK_OperatingSystem     [Type:int(11), Default:NULL, Null:YES]
#   * FK_Distro              [Type:int(11), Default:NULL, Null:YES]
#   * InheritsMacFromPC      [Type:tinyint(1), Default:0, Null:YES]
#   * ConfigureScript        [Type:varchar(100), Default:NULL, Null:YES]
#   * ManufacturerURL        [Type:varchar(100), Default:NULL, Null:YES]
#   * InternalURLSuffix      [Type:varchar(50), Default:NULL, Null:YES]
#   * WizardURL              [Type:varchar(50), Default:NULL, Null:YES]
#   * FK_Licensing           [Type:int(11), Default:NULL, Null:YES]
#   * FK_InfraredGroup       [Type:int(11), Default:NULL, Null:YES]
#   * FK_CommMethod          [Type:int(11), Default:NULL, Null:YES]
#   * FK_PnpLevel            [Type:int(11), Default:NULL, Null:YES]
#   * HelpURL                [Type:varchar(255), Default:NULL, Null:YES]
#   * psc_id                 [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch              [Type:int(11), Default:NULL, Null:YES]
#   * psc_user               [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen             [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict           [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_comm_method
# * belongs_to lmce_device_category
# * belongs_to lmce_distro
# * belongs_to lmce_infrared_group
# * belongs_to lmce_licensing
# * belongs_to lmce_manufacturer
# * belongs_to lmce_operating_system
# * belongs_to lmce_package
# * belongs_to lmce_pnp_level
# * belongs_to lmce_stability_status
# * has_many lmce_command_group_d_commands
# * has_many lmce_command_group_ds
# * has_many lmce_config_types
# * has_many lmce_design_objs
# * has_many lmce_device_categories
# * has_many lmce_device_datas
# * has_many lmce_device_template_design_objs
# * has_many lmce_device_template_device_category_controlled_vias
# * has_many lmce_device_template_device_command_groups
# * has_many lmce_device_template_device_datas
# * has_many lmce_device_template_device_template_controlled_vias
# * has_many lmce_device_template_device_template_relateds
# * has_many lmce_device_template_events
# * has_many lmce_device_template_infrared_groups
# * has_many lmce_device_template_media_types
# * has_many lmce_device_template_page_setups
# * has_many lmce_devices
# * has_many lmce_dhcp_devices
# * has_many lmce_events
# * has_many lmce_infrared_group_commands
# * has_many lmce_infrared_groups
# * has_many lmce_infrared_groups
# * has_many lmce_install_wizards
# * has_many lmce_media_types
# * has_many lmce_page_setups
# * has_many lmce_pnp_queues
# * has_many lmce_screen_design_objs
# * has_many lmce_screens
# * has_many lmce_startup_scripts
# * has_one lmce_device_template_av
# * has_one lmce_device_template_dsp_mode
# * has_one lmce_device_template_input
# * has_one lmce_device_template_output
#

class PlutoMain::LmceDeviceTemplate < PlutoMainDatabase
  set_table_name "DeviceTemplate"
  set_primary_key "PK_DeviceTemplate"

  # foreign key references
  # FK_DeviceTemplate references PlutoMain::LmcePnpLevel (FK_PnpLevel)
  belongs_to  :lmce_pnp_level,
      :class_name => "PlutoMain::LmcePnpLevel",
      :foreign_key => "FK_PnpLevel"

  # FK_DeviceTemplate references PlutoMain::LmceManufacturer (FK_Manufacturer)
  belongs_to  :lmce_manufacturer,
      :class_name => "PlutoMain::LmceManufacturer",
      :foreign_key => "FK_Manufacturer"

  # FK_DeviceTemplate references PlutoMain::LmceLicensing (FK_Licensing)
  belongs_to  :lmce_licensing,
      :class_name => "PlutoMain::LmceLicensing",
      :foreign_key => "FK_Licensing"

  # FK_DeviceTemplate references PlutoMain::LmceDeviceCategory (FK_DeviceCategory)
  belongs_to  :lmce_device_category,
      :class_name => "PlutoMain::LmceDeviceCategory",
      :foreign_key => "FK_DeviceCategory"

  # FK_DeviceTemplate references PlutoMain::LmcePackage (FK_Package)
  belongs_to  :lmce_package,
      :class_name => "PlutoMain::LmcePackage",
      :foreign_key => "FK_Package"

  # FK_DeviceTemplate references PlutoMain::LmceDistro (FK_Distro)
  belongs_to  :lmce_distro,
      :class_name => "PlutoMain::LmceDistro",
      :foreign_key => "FK_Distro"

  # FK_DeviceTemplate references PlutoMain::LmceInfraredGroup (FK_InfraredGroup)
  belongs_to  :lmce_infrared_group,
      :class_name => "PlutoMain::LmceInfraredGroup",
      :foreign_key => "FK_InfraredGroup"

  # FK_DeviceTemplate references PlutoMain::LmceStabilityStatus (FK_StabilityStatus)
  belongs_to  :lmce_stability_status,
      :class_name => "PlutoMain::LmceStabilityStatus",
      :foreign_key => "FK_StabilityStatus"

  # FK_DeviceTemplate references PlutoMain::LmceCommMethod (FK_CommMethod)
  belongs_to  :lmce_comm_method,
      :class_name => "PlutoMain::LmceCommMethod",
      :foreign_key => "FK_CommMethod"

  # FK_DeviceTemplate references PlutoMain::LmceOperatingSystem (FK_OperatingSystem)
  belongs_to  :lmce_operating_system,
      :class_name => "PlutoMain::LmceOperatingSystem",
      :foreign_key => "FK_OperatingSystem"

  # 1:1  (FK_DeviceTemplate)
  has_one  :lmce_device_template_av,
      :class_name => "PlutoMain::LmceDeviceTemplateAv",
      :foreign_key => "FK_DeviceTemplate"

  # n:n via through join table PlutoMain::LmceScreenDesignObj  (FK_DeviceTemplate)
  has_many  :lmce_screen_design_objs,
      :class_name => "PlutoMain::LmceScreenDesignObj",
      :foreign_key => "FK_DeviceTemplate"
  has_many  :lmce_screens,
      :through => :lmce_screen_design_objs

  # n:n via through join table PlutoMain::LmceDeviceTemplateDeviceData  (FK_DeviceTemplate)
  has_many  :lmce_device_template_device_datas,
      :class_name => "PlutoMain::LmceDeviceTemplateDeviceData",
      :foreign_key => "FK_DeviceTemplate"
  has_many  :lmce_device_datas,
      :through => :lmce_device_template_device_datas

  # n:n via through join table PlutoMain::LmceInfraredGroupCommand  (FK_DeviceTemplate)
  has_many  :lmce_infrared_group_commands,
      :class_name => "PlutoMain::LmceInfraredGroupCommand",
      :foreign_key => "FK_DeviceTemplate"
  has_many  :lmce_infrared_groups,
      :through => :lmce_infrared_group_commands

  # 1:n  (FK_DeviceTemplate)
  has_many  :lmce_install_wizards,
      :class_name => "PlutoMain::LmceInstallWizard",
      :foreign_key => "FK_DeviceTemplate"

  # n:n via through join table PlutoMain::LmceDeviceTemplateInfraredGroup  (FK_DeviceTemplate)
  has_many  :lmce_device_template_infrared_groups,
      :class_name => "PlutoMain::LmceDeviceTemplateInfraredGroup",
      :foreign_key => "FK_DeviceTemplate"
  has_many  :lmce_infrared_groups,
      :through => :lmce_device_template_infrared_groups

  # n:n via through join table PlutoMain::LmceDeviceTemplateEvent  (FK_DeviceTemplate)
  has_many  :lmce_device_template_events,
      :class_name => "PlutoMain::LmceDeviceTemplateEvent",
      :foreign_key => "FK_DeviceTemplate"
  has_many  :lmce_events,
      :through => :lmce_device_template_events

  # n:n via through join table PlutoMain::LmceDeviceTemplateDeviceCommandGroup  (FK_DeviceTemplate)
  has_many  :lmce_device_template_device_command_groups,
      :class_name => "PlutoMain::LmceDeviceTemplateDeviceCommandGroup",
      :foreign_key => "FK_DeviceTemplate"

  # 1:n  (FK_DeviceTemplate)
  has_many  :lmce_dhcp_devices,
      :class_name => "PlutoMain::LmceDhcpDevice",
      :foreign_key => "FK_DeviceTemplate"

  # n:n via through join table PlutoMain::LmceDeviceTemplateDeviceTemplateControlledVia  (FK_DeviceTemplate)
  has_many  :lmce_device_template_device_template_controlled_vias,
      :class_name => "PlutoMain::LmceDeviceTemplateDeviceTemplateControlledVia",
      :foreign_key => "FK_DeviceTemplate"

  # 1:n  (FK_DeviceTemplate)
  has_many  :lmce_devices,
      :class_name => "PlutoMain::LmceDevice",
      :foreign_key => "FK_DeviceTemplate"

  # 1:n  (FK_DeviceTemplate)
  has_many  :lmce_pnp_queues,
      :class_name => "PlutoMain::LmcePnpQueue",
      :foreign_key => "FK_DeviceTemplate"

  # 1:1  (FK_DeviceTemplate)
  has_one  :lmce_device_template_dsp_mode,
      :class_name => "PlutoMain::LmceDeviceTemplateDspMode",
      :foreign_key => "FK_DeviceTemplate"

  # n:n via through join table PlutoMain::LmceDeviceTemplatePageSetup  (FK_DeviceTemplate)
  has_many  :lmce_device_template_page_setups,
      :class_name => "PlutoMain::LmceDeviceTemplatePageSetup",
      :foreign_key => "FK_DeviceTemplate"
  has_many  :lmce_page_setups,
      :through => :lmce_device_template_page_setups

  # n:n via through join table PlutoMain::LmceDeviceTemplateDeviceTemplateRelated  (FK_DeviceTemplate)
  has_many  :lmce_device_template_device_template_relateds,
      :class_name => "PlutoMain::LmceDeviceTemplateDeviceTemplateRelated",
      :foreign_key => "FK_DeviceTemplate"

  # 1:1  (FK_DeviceTemplate)
  has_one  :lmce_device_template_output,
      :class_name => "PlutoMain::LmceDeviceTemplateOutput",
      :foreign_key => "FK_DeviceTemplate"

  # n:n via through join table PlutoMain::LmceCommandGroupDCommand  (FK_DeviceTemplate)
  has_many  :lmce_command_group_d_commands,
      :class_name => "PlutoMain::LmceCommandGroupDCommand",
      :foreign_key => "FK_DeviceTemplate"
  has_many  :lmce_command_group_ds,
      :through => :lmce_command_group_d_commands

  # 1:n  (FK_DeviceTemplate)
  has_many  :lmce_config_types,
      :class_name => "PlutoMain::LmceConfigType",
      :foreign_key => "FK_DeviceTemplate"

  # n:n via through join table PlutoMain::LmceDeviceTemplateDeviceCategoryControlledVia  (FK_DeviceTemplate)
  has_many  :lmce_device_template_device_category_controlled_vias,
      :class_name => "PlutoMain::LmceDeviceTemplateDeviceCategoryControlledVia",
      :foreign_key => "FK_DeviceTemplate"
  has_many  :lmce_device_categories,
      :through => :lmce_device_template_device_category_controlled_vias

  # n:n via through join table PlutoMain::LmceDeviceTemplateMediaType  (FK_DeviceTemplate)
  has_many  :lmce_device_template_media_types,
      :class_name => "PlutoMain::LmceDeviceTemplateMediaType",
      :foreign_key => "FK_DeviceTemplate"
  has_many  :lmce_media_types,
      :through => :lmce_device_template_media_types

  # n:n via through join table PlutoMain::LmceDeviceTemplateDesignObj  (FK_DeviceTemplate)
  has_many  :lmce_device_template_design_objs,
      :class_name => "PlutoMain::LmceDeviceTemplateDesignObj",
      :foreign_key => "FK_DeviceTemplate"
  has_many  :lmce_design_objs,
      :through => :lmce_device_template_design_objs

  # 1:1  (FK_DeviceTemplate)
  has_one  :lmce_device_template_input,
      :class_name => "PlutoMain::LmceDeviceTemplateInput",
      :foreign_key => "FK_DeviceTemplate"

  # 1:n  (FK_DeviceTemplate)
  has_many  :lmce_startup_scripts,
      :class_name => "PlutoMain::LmceStartupScript",
      :foreign_key => "FK_DeviceTemplate"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

