# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.CommandGroup_D_Command_CommandParameter
# Through Join Table
#
# * primary keys: FK_CommandGroup_D_Command,FK_CommandParameter
# * foreign keys: FK_CommandGroup_D_Command,FK_CommandParameter
# * external keys: 
#
# == References
# * PlutoMain::LmceCommandParameter
# * PlutoMain::LmceCommandGroupDCommand
#
# == Referenced By
#
# == Database Table Columns
#   * FK_CommandGroup_D_Command    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_CommandParameter          [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * IK_CommandParameter          [Type:text, Default:NULL, Null:YES]
#   * psc_id                       [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                    [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                     [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                   [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                      [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                 [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_command_group_d_command
# * belongs_to lmce_command_parameter
#

class PlutoMain::LmceCommandGroupDCommandCommandParameter < PlutoMainDatabase
  set_table_name "CommandGroup_D_Command_CommandParameter"
  set_primary_keys "FK_CommandGroup_D_Command", "FK_CommandParameter"

  # foreign key references
  # FK_CommandGroup_D_Command_CommandParameter references PlutoMain::LmceCommandParameter (FK_CommandParameter)
  belongs_to  :lmce_command_parameter,
      :class_name => "PlutoMain::LmceCommandParameter",
      :foreign_key => "FK_CommandParameter"

  # FK_CommandGroup_D_Command_CommandParameter references PlutoMain::LmceCommandGroupDCommand (FK_CommandGroup_D_Command)
  belongs_to  :lmce_command_group_d_command,
      :class_name => "PlutoMain::LmceCommandGroupDCommand",
      :foreign_key => "FK_CommandGroup_D_Command"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

