# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Region
#
# * primary keys: PK_Region
# * foreign keys: FK_Country
# * external keys: 
#
# == References
# * PlutoMain::LmceCountry
#
# == Referenced By
# * PlutoMain::LmceCity
#
# == Database Table Columns
#   * PK_Region     [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_Country    [Type:int(11), Default:0, Null:NO]
#   * Region        [Type:varchar(45), Default:NULL, Null:YES]
#   * Code          [Type:varchar(8), Default:NULL, Null:YES]
#   * ADM1Code      [Type:varchar(4), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_country
# * has_many lmce_cities
#

class PlutoMain::LmceRegion < PlutoMainDatabase
  set_table_name "Region"
  set_primary_key "PK_Region"

  # foreign key references
  # FK_Region references PlutoMain::LmceCountry (FK_Country)
  belongs_to  :lmce_country,
      :class_name => "PlutoMain::LmceCountry",
      :foreign_key => "FK_Country"

  # 1:n  (FK_Region)
  has_many  :lmce_cities,
      :class_name => "PlutoMain::LmceCity",
      :foreign_key => "FK_Region"


  # add your model extensions after this line

end

