# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Pipe
#
# * primary keys: PK_Pipe
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceDeviceTemplateDeviceCategoryControlledViaPipe
# * PlutoMain::LmceMediaType
# * PlutoMain::LmceDeviceTemplateDeviceTemplateControlledViaPipe
# * PlutoMain::LmceCommandPipe
# * PlutoMain::LmceDeviceDevicePipe
#
# == Database Table Columns
#   * PK_Pipe         [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description     [Type:varchar(50), Default:NULL, Null:NO]
#   * Define          [Type:varchar(10), Default:NULL, Null:YES]
#   * psc_id          [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch       [Type:int(11), Default:NULL, Null:YES]
#   * psc_user        [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen      [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod         [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict    [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_command_pipes
# * has_many lmce_commands
# * has_many lmce_device_device_pipes
# * has_many lmce_device_template_device_category_controlled_via_pipes
# * has_many lmce_device_template_device_category_controlled_vias
# * has_many lmce_device_template_device_template_controlled_via_pipes
# * has_many lmce_device_template_device_template_controlled_vias
# * has_many lmce_media_types
#

class PlutoMain::LmcePipe < PlutoMainDatabase
  set_table_name "Pipe"
  set_primary_key "PK_Pipe"

  # foreign key references
  # n:n via through join table PlutoMain::LmceDeviceTemplateDeviceCategoryControlledViaPipe  (FK_Pipe)
  has_many  :lmce_device_template_device_category_controlled_via_pipes,
      :class_name => "PlutoMain::LmceDeviceTemplateDeviceCategoryControlledViaPipe",
      :foreign_key => "FK_Pipe"
  has_many  :lmce_device_template_device_category_controlled_vias,
      :through => :lmce_device_template_device_category_controlled_via_pipes

  # 1:n  (FK_Pipe)
  has_many  :lmce_media_types,
      :class_name => "PlutoMain::LmceMediaType",
      :foreign_key => "FK_Pipe"

  # n:n via through join table PlutoMain::LmceDeviceTemplateDeviceTemplateControlledViaPipe  (FK_Pipe)
  has_many  :lmce_device_template_device_template_controlled_via_pipes,
      :class_name => "PlutoMain::LmceDeviceTemplateDeviceTemplateControlledViaPipe",
      :foreign_key => "FK_Pipe"
  has_many  :lmce_device_template_device_template_controlled_vias,
      :through => :lmce_device_template_device_template_controlled_via_pipes

  # n:n via through join table PlutoMain::LmceCommandPipe  (FK_Pipe)
  has_many  :lmce_command_pipes,
      :class_name => "PlutoMain::LmceCommandPipe",
      :foreign_key => "FK_Pipe"
  has_many  :lmce_commands,
      :through => :lmce_command_pipes

  # 1:n  (FK_Pipe)
  has_many  :lmce_device_device_pipes,
      :class_name => "PlutoMain::LmceDeviceDevicePipe",
      :foreign_key => "FK_Pipe"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

