# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Command
#
# * primary keys: PK_Command
# * foreign keys: FK_CommandCategory
# * external keys: 
#
# == References
# * PlutoMain::LmceCommandCategory
#
# == Referenced By
# * PlutoMain::LmceDeviceCommandGroupCommand
# * PlutoMain::LmceCommandGroupDCommand
# * PlutoMain::LmceCommandCommandParameter
# * PlutoMain::LmceCommandPipe
# * PlutoMain::LmceDeviceTemplateDspMode
# * PlutoMain::LmceDeviceTemplateOutput
# * PlutoMain::LmceInfraredGroupCommand
# * PlutoMain::LmceDeviceCommand
# * PlutoMain::LmceDeviceTemplateInput
# * PlutoMain::LmceCommandGroupCommand
#
# == Database Table Columns
#   * PK_Command            [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description           [Type:varchar(50), Default:NULL, Null:NO]
#   * Define                [Type:varchar(50), Default:NULL, Null:YES]
#   * FK_CommandCategory    [Type:int(11), Default:0, Null:NO]
#   * AVCommand             [Type:tinyint(4), Default:0, Null:NO]
#   * Comments              [Type:text, Default:NULL, Null:YES]
#   * Log                   [Type:tinyint(1), Default:1, Null:NO]
#   * psc_id                [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch             [Type:int(11), Default:NULL, Null:YES]
#   * psc_user              [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen            [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod               [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict          [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_command_category
# * has_many lmce_command_command_parameters
# * has_many lmce_command_group_commands
# * has_many lmce_command_group_d_commands
# * has_many lmce_command_group_ds
# * has_many lmce_command_groups
# * has_many lmce_command_parameters
# * has_many lmce_command_pipes
# * has_many lmce_device_command_group_commands
# * has_many lmce_device_commands
# * has_many lmce_devices
# * has_many lmce_infrared_group_commands
# * has_many lmce_infrared_groups
# * has_many lmce_pipes
# * has_one lmce_device_template_dsp_mode
# * has_one lmce_device_template_input
# * has_one lmce_device_template_output
#

class PlutoMain::LmceCommand < PlutoMainDatabase
  set_table_name "Command"
  set_primary_key "PK_Command"

  # foreign key references
  # FK_Command references PlutoMain::LmceCommandCategory (FK_CommandCategory)
  belongs_to  :lmce_command_category,
      :class_name => "PlutoMain::LmceCommandCategory",
      :foreign_key => "FK_CommandCategory"

  # n:n via through join table PlutoMain::LmceDeviceCommandGroupCommand  (FK_Command)
  has_many  :lmce_device_command_group_commands,
      :class_name => "PlutoMain::LmceDeviceCommandGroupCommand",
      :foreign_key => "FK_Command"

  # n:n via through join table PlutoMain::LmceCommandGroupDCommand  (FK_Command)
  has_many  :lmce_command_group_d_commands,
      :class_name => "PlutoMain::LmceCommandGroupDCommand",
      :foreign_key => "FK_Command"
  has_many  :lmce_command_group_ds,
      :through => :lmce_command_group_d_commands

  # n:n via through join table PlutoMain::LmceCommandCommandParameter  (FK_Command)
  has_many  :lmce_command_command_parameters,
      :class_name => "PlutoMain::LmceCommandCommandParameter",
      :foreign_key => "FK_Command"
  has_many  :lmce_command_parameters,
      :through => :lmce_command_command_parameters

  # n:n via through join table PlutoMain::LmceCommandPipe  (FK_Command)
  has_many  :lmce_command_pipes,
      :class_name => "PlutoMain::LmceCommandPipe",
      :foreign_key => "FK_Command"
  has_many  :lmce_pipes,
      :through => :lmce_command_pipes

  # 1:1  (FK_Command)
  has_one  :lmce_device_template_dsp_mode,
      :class_name => "PlutoMain::LmceDeviceTemplateDspMode",
      :foreign_key => "FK_Command"

  # 1:1  (FK_Command)
  has_one  :lmce_device_template_output,
      :class_name => "PlutoMain::LmceDeviceTemplateOutput",
      :foreign_key => "FK_Command"

  # n:n via through join table PlutoMain::LmceInfraredGroupCommand  (FK_Command)
  has_many  :lmce_infrared_group_commands,
      :class_name => "PlutoMain::LmceInfraredGroupCommand",
      :foreign_key => "FK_Command"
  has_many  :lmce_infrared_groups,
      :through => :lmce_infrared_group_commands

  # n:n via through join table PlutoMain::LmceDeviceCommand  (FK_Command)
  has_many  :lmce_device_commands,
      :class_name => "PlutoMain::LmceDeviceCommand",
      :foreign_key => "FK_Command"
  has_many  :lmce_devices,
      :through => :lmce_device_commands

  # 1:1  (FK_Command)
  has_one  :lmce_device_template_input,
      :class_name => "PlutoMain::LmceDeviceTemplateInput",
      :foreign_key => "FK_Command"

  # n:n via through join table PlutoMain::LmceCommandGroupCommand  (FK_Command)
  has_many  :lmce_command_group_commands,
      :class_name => "PlutoMain::LmceCommandGroupCommand",
      :foreign_key => "FK_Command"
  has_many  :lmce_command_groups,
      :through => :lmce_command_group_commands

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

