# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.UI
#
# * primary keys: PK_UI
# * foreign keys: FK_UI_Alt
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceSkin
# * PlutoMain::LmceStyleVariation
# * PlutoMain::LmceScreenDesignObj
# * PlutoMain::LmceSize
# * PlutoMain::LmceDesignObjVariation
#
# == Database Table Columns
#   * PK_UI                [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description          [Type:varchar(30), Default:NULL, Null:YES]
#   * Define               [Type:varchar(25), Default:NULL, Null:YES]
#   * IncludeStandardUI    [Type:tinyint(1), Default:NULL, Null:YES]
#   * Version              [Type:int(11), Default:NULL, Null:YES]
#   * FK_UI_Alt            [Type:int(11), Default:NULL, Null:YES]
#   * psc_id               [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch            [Type:int(11), Default:NULL, Null:YES]
#   * psc_user             [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod              [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict         [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to alt
# * has_many lmce_design_obj_variations
# * has_many lmce_screen_design_objs
# * has_many lmce_screens
# * has_many lmce_sizes
# * has_many lmce_skins
# * has_many lmce_style_variations
# * has_many ui_alts
#

class PlutoMain::LmceUi < PlutoMainDatabase
  set_table_name "UI"
  set_primary_key "PK_UI"

  # foreign key references
  # 1:n  (FK_UI)
  has_many  :lmce_skins,
      :class_name => "PlutoMain::LmceSkin",
      :foreign_key => "FK_UI"

  # 1:n  (FK_UI)
  has_many  :lmce_style_variations,
      :class_name => "PlutoMain::LmceStyleVariation",
      :foreign_key => "FK_UI"

  # n:n via through join table PlutoMain::LmceScreenDesignObj  (FK_UI)
  has_many  :lmce_screen_design_objs,
      :class_name => "PlutoMain::LmceScreenDesignObj",
      :foreign_key => "FK_UI"
  has_many  :lmce_screens,
      :through => :lmce_screen_design_objs

  # 1:n  (FK_UI)
  has_many  :lmce_sizes,
      :class_name => "PlutoMain::LmceSize",
      :foreign_key => "FK_UI"

  # 1:n  (FK_UI)
  has_many  :lmce_design_obj_variations,
      :class_name => "PlutoMain::LmceDesignObjVariation",
      :foreign_key => "FK_UI"

  # self references
  belongs_to  :alt,
      :class_name => "PlutoMain::LmceUi",
      :foreign_key => "FK_UI_Alt"
  has_many  :ui_alts,
      :class_name => "PlutoMain::LmceUi",
      :foreign_key => "FK_UI_Alt"
  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

