# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DesignObjVariation_DesignObj
#
# * primary keys: PK_DesignObjVariation_DesignObj
# * foreign keys: FK_DesignObjVariation_Parent,FK_DesignObj_Child
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMain::LmceDesignObjVariationDesignObjSkinLanguage
#
# == Database Table Columns
#   * PK_DesignObjVariation_DesignObj    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_DesignObjVariation_Parent       [Type:int(11), Default:NULL, Null:YES]
#   * FK_DesignObj_Child                 [Type:int(11), Default:NULL, Null:YES]
#   * psc_id                             [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                          [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                           [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                         [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                            [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                       [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_design_obj_variation_design_obj_skin_languages
#

class PlutoMain::LmceDesignObjVariationDesignObj < PlutoMainDatabase
  set_table_name "DesignObjVariation_DesignObj"
  set_primary_key "PK_DesignObjVariation_DesignObj"

  # foreign key references
  # 1:n  (FK_DesignObjVariation_DesignObj)
  has_many  :lmce_design_obj_variation_design_obj_skin_languages,
      :class_name => "PlutoMain::LmceDesignObjVariationDesignObjSkinLanguage",
      :foreign_key => "FK_DesignObjVariation_DesignObj"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

