# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DeviceTemplate_AV
#
# * primary keys: FK_DeviceTemplate
# * foreign keys: FK_DeviceTemplate
# * external keys: 
#
# == References
# * PlutoMain::LmceDeviceTemplate
#
# == Referenced By
#
# == Database Table Columns
#   * FK_DeviceTemplate      [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * IR_PowerDelay          [Type:int(11), Default:0, Null:NO]
#   * IR_ModeDelay           [Type:int(11), Default:0, Null:NO]
#   * DigitDelay             [Type:int(11), Default:0, Null:NO]
#   * TogglePower            [Type:int(11), Default:0, Null:NO]
#   * ToggleDSP              [Type:int(11), Default:0, Null:NO]
#   * ToggleInput            [Type:int(11), Default:0, Null:NO]
#   * ToggleOutput           [Type:int(11), Default:0, Null:NO]
#   * NumericEntry           [Type:varchar(4), Default:NULL, Null:YES]
#   * MonitorInputChanges    [Type:tinyint(1), Default:0, Null:NO]
#   * RepeatIR               [Type:int(11), Default:4, Null:NO]
#   * RepeatVolume           [Type:int(11), Default:2, Null:NO]
#   * psc_id                 [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch              [Type:int(11), Default:NULL, Null:YES]
#   * psc_user               [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen             [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict           [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device_template
#

class PlutoMain::LmceDeviceTemplateAv < PlutoMainDatabase
  set_table_name "DeviceTemplate_AV"
  set_primary_key "FK_DeviceTemplate"

  # foreign key references
  # FK_DeviceTemplate_AV references PlutoMain::LmceDeviceTemplate (FK_DeviceTemplate)
  belongs_to  :lmce_device_template,
      :class_name => "PlutoMain::LmceDeviceTemplate",
      :foreign_key => "FK_DeviceTemplate"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

