# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DeviceCategory_Event
# Through Join Table
#
# * primary keys: FK_DeviceCategory,FK_Event
# * foreign keys: FK_DeviceCategory,FK_Event
# * external keys: 
#
# == References
# * PlutoMain::LmceEvent
# * PlutoMain::LmceDeviceCategory
#
# == Referenced By
#
# == Database Table Columns
#   * FK_DeviceCategory    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Event             [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * psc_id               [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch            [Type:int(11), Default:NULL, Null:YES]
#   * psc_user             [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod              [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict         [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device_category
# * belongs_to lmce_event
#

class PlutoMain::LmceDeviceCategoryEvent < PlutoMainDatabase
  set_table_name "DeviceCategory_Event"
  set_primary_keys "FK_DeviceCategory", "FK_Event"

  # foreign key references
  # FK_DeviceCategory_Event references PlutoMain::LmceEvent (FK_Event)
  belongs_to  :lmce_event,
      :class_name => "PlutoMain::LmceEvent",
      :foreign_key => "FK_Event"

  # FK_DeviceCategory_Event references PlutoMain::LmceDeviceCategory (FK_DeviceCategory)
  belongs_to  :lmce_device_category,
      :class_name => "PlutoMain::LmceDeviceCategory",
      :foreign_key => "FK_DeviceCategory"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

