# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.InfraredGroup
#
# * primary keys: PK_InfraredGroup
# * foreign keys: FK_DeviceCategory,FK_Manufacturer,FK_CommMethod
# * external keys: 
#
# == References
# * PlutoMain::LmceManufacturer
# * PlutoMain::LmceDeviceCategory
# * PlutoMain::LmceCommMethod
#
# == Referenced By
# * PlutoMain::LmceDeviceTemplateInfraredGroup
# * PlutoMain::LmceDeviceTemplate
# * PlutoMain::LmceInfraredGroupCommand
#
# == Database Table Columns
#   * PK_InfraredGroup     [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_DeviceCategory    [Type:int(11), Default:0, Null:NO]
#   * FK_Manufacturer      [Type:int(11), Default:0, Null:NO]
#   * Description          [Type:varchar(50), Default:NULL, Null:YES]
#   * FK_CommMethod        [Type:int(11), Default:1, Null:NO]
#   * psc_id               [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch            [Type:int(11), Default:NULL, Null:YES]
#   * psc_user             [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod              [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict         [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_comm_method
# * belongs_to lmce_device_category
# * belongs_to lmce_manufacturer
# * has_many lmce_commands
# * has_many lmce_device_template_infrared_groups
# * has_many lmce_device_templates
# * has_many lmce_device_templates
# * has_many lmce_infrared_group_commands
#

class PlutoMain::LmceInfraredGroup < PlutoMainDatabase
  set_table_name "InfraredGroup"
  set_primary_key "PK_InfraredGroup"

  # foreign key references
  # FK_InfraredGroup references PlutoMain::LmceManufacturer (FK_Manufacturer)
  belongs_to  :lmce_manufacturer,
      :class_name => "PlutoMain::LmceManufacturer",
      :foreign_key => "FK_Manufacturer"

  # FK_InfraredGroup references PlutoMain::LmceDeviceCategory (FK_DeviceCategory)
  belongs_to  :lmce_device_category,
      :class_name => "PlutoMain::LmceDeviceCategory",
      :foreign_key => "FK_DeviceCategory"

  # FK_InfraredGroup references PlutoMain::LmceCommMethod (FK_CommMethod)
  belongs_to  :lmce_comm_method,
      :class_name => "PlutoMain::LmceCommMethod",
      :foreign_key => "FK_CommMethod"

  # n:n via through join table PlutoMain::LmceDeviceTemplateInfraredGroup  (FK_InfraredGroup)
  has_many  :lmce_device_template_infrared_groups,
      :class_name => "PlutoMain::LmceDeviceTemplateInfraredGroup",
      :foreign_key => "FK_InfraredGroup"
  has_many  :lmce_device_templates,
      :through => :lmce_device_template_infrared_groups

  # 1:n  (FK_InfraredGroup)
  has_many  :lmce_device_templates,
      :class_name => "PlutoMain::LmceDeviceTemplate",
      :foreign_key => "FK_InfraredGroup"

  # n:n via through join table PlutoMain::LmceInfraredGroupCommand  (FK_InfraredGroup)
  has_many  :lmce_infrared_group_commands,
      :class_name => "PlutoMain::LmceInfraredGroupCommand",
      :foreign_key => "FK_InfraredGroup"
  has_many  :lmce_commands,
      :through => :lmce_infrared_group_commands

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

