# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Package_Package
# Through Join Table
#
# * primary keys: FK_Package,FK_Package_DependsOn
# * foreign keys: FK_Package,FK_Package_DependsOn
# * external keys: 
#
# == References
# * PlutoMain::LmcePackage
#
# == Referenced By
#
# == Database Table Columns
#   * FK_Package              [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Package_DependsOn    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * OnlyToBuild             [Type:tinyint(1), Default:0, Null:NO]
#   * PreDependency           [Type:tinyint(1), Default:0, Null:NO]
#   * psc_id                  [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch               [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen              [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                 [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict            [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to depends_on
# * belongs_to lmce_package
# * has_many package_depends_ons
#

class PlutoMain::LmcePackagePackage < PlutoMainDatabase
  set_table_name "Package_Package"
  set_primary_keys "FK_Package", "FK_Package_DependsOn"

  # foreign key references
  # FK_Package_Package references PlutoMain::LmcePackage (FK_Package)
  belongs_to  :lmce_package,
      :class_name => "PlutoMain::LmcePackage",
      :foreign_key => "FK_Package"

  # self references
  belongs_to  :depends_on,
      :class_name => "PlutoMain::LmcePackagePackage",
      :foreign_key => "FK_Package_DependsOn"
  has_many  :package_depends_ons,
      :class_name => "PlutoMain::LmcePackagePackage",
      :foreign_key => "FK_Package_DependsOn"
  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

