# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Room
#
# * primary keys: PK_Room
# * foreign keys: FK_Installation,FK_RoomType,FK_Icon,FK_FloorplanObjectType
# * external keys: 
#
# == References
# * PlutoMain::LmceFloorplanObjectType
# * PlutoMain::LmceIcon
# * PlutoMain::LmceRoomType
# * PlutoMain::LmceInstallation
#
# == Referenced By
# * PlutoMain::LmceEntertainArea
# * PlutoMain::LmceDevice
# * PlutoMain::LmceRoomUser
# * PlutoMain::LmceCommandGroupRoom
#
# == Database Table Columns
#   * PK_Room                   [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_Installation           [Type:int(11), Default:0, Null:NO]
#   * FK_RoomType               [Type:int(11), Default:NULL, Null:YES]
#   * Description               [Type:varchar(30), Default:NULL, Null:NO]
#   * FK_Icon                   [Type:int(11), Default:NULL, Null:YES]
#   * ManuallyConfigureEA       [Type:tinyint(1), Default:0, Null:YES]
#   * HideFromOrbiter           [Type:tinyint(1), Default:0, Null:NO]
#   * FK_FloorplanObjectType    [Type:int(11), Default:NULL, Null:YES]
#   * FloorplanInfo             [Type:text, Default:NULL, Null:YES]
#   * psc_id                    [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                 [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                  [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                   [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict              [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_floorplan_object_type
# * belongs_to lmce_icon
# * belongs_to lmce_installation
# * belongs_to lmce_room_type
# * has_many lmce_command_group_rooms
# * has_many lmce_command_groups
# * has_many lmce_devices
# * has_many lmce_entertain_areas
# * has_many lmce_room_users
# * has_many lmce_users
#

class PlutoMain::LmceRoom < PlutoMainDatabase
  set_table_name "Room"
  set_primary_key "PK_Room"

  # foreign key references
  # FK_Room references PlutoMain::LmceFloorplanObjectType (FK_FloorplanObjectType)
  belongs_to  :lmce_floorplan_object_type,
      :class_name => "PlutoMain::LmceFloorplanObjectType",
      :foreign_key => "FK_FloorplanObjectType"

  # FK_Room references PlutoMain::LmceIcon (FK_Icon)
  belongs_to  :lmce_icon,
      :class_name => "PlutoMain::LmceIcon",
      :foreign_key => "FK_Icon"

  # FK_Room references PlutoMain::LmceRoomType (FK_RoomType)
  belongs_to  :lmce_room_type,
      :class_name => "PlutoMain::LmceRoomType",
      :foreign_key => "FK_RoomType"

  # FK_Room references PlutoMain::LmceInstallation (FK_Installation)
  belongs_to  :lmce_installation,
      :class_name => "PlutoMain::LmceInstallation",
      :foreign_key => "FK_Installation"

  # 1:n  (FK_Room)
  has_many  :lmce_entertain_areas,
      :class_name => "PlutoMain::LmceEntertainArea",
      :foreign_key => "FK_Room"

  # 1:n  (FK_Room)
  has_many  :lmce_devices,
      :class_name => "PlutoMain::LmceDevice",
      :foreign_key => "FK_Room"

  # n:n via through join table PlutoMain::LmceRoomUser  (FK_Room)
  has_many  :lmce_room_users,
      :class_name => "PlutoMain::LmceRoomUser",
      :foreign_key => "FK_Room"
  has_many  :lmce_users,
      :through => :lmce_room_users

  # n:n via through join table PlutoMain::LmceCommandGroupRoom  (FK_Room)
  has_many  :lmce_command_group_rooms,
      :class_name => "PlutoMain::LmceCommandGroupRoom",
      :foreign_key => "FK_Room"
  has_many  :lmce_command_groups,
      :through => :lmce_command_group_rooms

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

