# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.StartupScript
#
# * primary keys: PK_StartupScript
# * foreign keys: FK_DeviceTemplate
# * external keys: 
#
# == References
# * PlutoMain::LmceDeviceTemplate
#
# == Referenced By
# * PlutoMain::LmceDeviceStartupScript
#
# == Database Table Columns
#   * PK_StartupScript     [Type:int(10), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * When                 [Type:char(1), Default:S, Null:YES]
#   * Command              [Type:varchar(100), Default:NULL, Null:NO]
#   * Description          [Type:text, Default:NULL, Null:NO]
#   * ConfigureOnly        [Type:tinyint(1), Default:0, Null:NO]
#   * Parameter_Syntax     [Type:text, Default:NULL, Null:NO]
#   * Core_Boot_Order      [Type:int(11), Default:99, Null:NO]
#   * Core_Background      [Type:int(1), Default:0, Null:NO]
#   * Core_Enabled         [Type:int(1), Default:1, Null:NO]
#   * Core_Parameter       [Type:varchar(100), Default:NULL, Null:NO]
#   * MD_Boot_Order        [Type:int(11), Default:99, Null:NO]
#   * MD_Background        [Type:tinyint(1), Default:0, Null:NO]
#   * MD_Enabled           [Type:tinyint(1), Default:1, Null:NO]
#   * MD_Parameter         [Type:varchar(100), Default:NULL, Null:NO]
#   * Hybrid_Boot_Order    [Type:int(11), Default:99, Null:NO]
#   * Hybrid_Background    [Type:tinyint(1), Default:0, Null:NO]
#   * Hybrid_Enabled       [Type:tinyint(1), Default:1, Null:NO]
#   * Hybrid_Parameter     [Type:varchar(100), Default:NULL, Null:NO]
#   * FK_DeviceTemplate    [Type:int(11), Default:NULL, Null:YES]
#   * psc_id               [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch            [Type:int(11), Default:NULL, Null:YES]
#   * psc_user             [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod              [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict         [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device_template
# * has_many lmce_device_startup_scripts
# * has_many lmce_devices
#

class PlutoMain::LmceStartupScript < PlutoMainDatabase
  set_table_name "StartupScript"
  set_primary_key "PK_StartupScript"

  # foreign key references
  # FK_StartupScript references PlutoMain::LmceDeviceTemplate (FK_DeviceTemplate)
  belongs_to  :lmce_device_template,
      :class_name => "PlutoMain::LmceDeviceTemplate",
      :foreign_key => "FK_DeviceTemplate"

  # n:n via through join table PlutoMain::LmceDeviceStartupScript  (FK_StartupScript)
  has_many  :lmce_device_startup_scripts,
      :class_name => "PlutoMain::LmceDeviceStartupScript",
      :foreign_key => "FK_StartupScript"
  has_many  :lmce_devices,
      :through => :lmce_device_startup_scripts

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

