# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DesignObjVariation_Text
# Through Join Table
#
# * primary keys: PK_DesignObjVariation_Text
# * foreign keys: FK_DesignObjVariation,FK_Text,FK_Text_OverrideFromHeader
# * external keys: 
#
# == References
# * PlutoMain::LmceDesignObjVariation
# * PlutoMain::LmceText
#
# == Referenced By
# * PlutoMain::LmceDesignObjVariationTextSkinLanguage
#
# == Database Table Columns
#   * PK_DesignObjVariation_Text    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_DesignObjVariation         [Type:int(11), Default:0, Null:NO]
#   * FK_Text                       [Type:int(11), Default:0, Null:NO]
#   * FK_Text_OverrideFromHeader    [Type:int(11), Default:NULL, Null:YES]
#   * psc_id                        [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch                     [Type:int(11), Default:NULL, Null:YES]
#   * psc_user                      [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen                    [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                       [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict                  [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_design_obj_variation
# * belongs_to lmce_text
# * has_many lmce_design_obj_variation_text_skin_languages
#

class PlutoMain::LmceDesignObjVariationText < PlutoMainDatabase
  set_table_name "DesignObjVariation_Text"
  set_primary_key "PK_DesignObjVariation_Text"

  # foreign key references
  # FK_DesignObjVariation_Text references PlutoMain::LmceDesignObjVariation (FK_DesignObjVariation)
  belongs_to  :lmce_design_obj_variation,
      :class_name => "PlutoMain::LmceDesignObjVariation",
      :foreign_key => "FK_DesignObjVariation"

  # FK_DesignObjVariation_Text references PlutoMain::LmceText (FK_Text)
  belongs_to  :lmce_text,
      :class_name => "PlutoMain::LmceText",
      :foreign_key => "FK_Text"

  # 1:n  (FK_DesignObjVariation_Text)
  has_many  :lmce_design_obj_variation_text_skin_languages,
      :class_name => "PlutoMain::LmceDesignObjVariationTextSkinLanguage",
      :foreign_key => "FK_DesignObjVariation_Text"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

