# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.Screen_CommandParameter
# Through Join Table
#
# * primary keys: FK_Screen,FK_CommandParameter
# * foreign keys: FK_Screen,FK_CommandParameter
# * external keys: 
#
# == References
# * PlutoMain::LmceCommandParameter
# * PlutoMain::LmceScreen
#
# == Referenced By
#
# == Database Table Columns
#   * FK_Screen              [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_CommandParameter    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * Description            [Type:text, Default:NULL, Null:YES]
#   * psc_id                 [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch              [Type:int(11), Default:NULL, Null:YES]
#   * psc_user               [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen             [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod                [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict           [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_command_parameter
# * belongs_to lmce_screen
#

class PlutoMain::LmceScreenCommandParameter < PlutoMainDatabase
  set_table_name "Screen_CommandParameter"
  set_primary_keys "FK_Screen", "FK_CommandParameter"

  # foreign key references
  # FK_Screen_CommandParameter references PlutoMain::LmceCommandParameter (FK_CommandParameter)
  belongs_to  :lmce_command_parameter,
      :class_name => "PlutoMain::LmceCommandParameter",
      :foreign_key => "FK_CommandParameter"

  # FK_Screen_CommandParameter references PlutoMain::LmceScreen (FK_Screen)
  belongs_to  :lmce_screen,
      :class_name => "PlutoMain::LmceScreen",
      :foreign_key => "FK_Screen"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

