# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:04 -0500 2008
#
# == Synopsis
# Database Table: pluto_main.DeviceData
#
# * primary keys: PK_DeviceData
# * foreign keys: FK_ParameterType
# * external keys: 
#
# == References
# * PlutoMain::LmceParameterType
#
# == Referenced By
# * PlutoMain::LmceDeviceTemplateDeviceData
# * PlutoMain::LmceDhcpDeviceDeviceData
# * PlutoMain::LmceDeviceDeviceData
# * PlutoMain::LmceDeviceCategoryDeviceData
#
# == Database Table Columns
#   * PK_DeviceData       [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description         [Type:varchar(30), Default:NULL, Null:NO]
#   * Define              [Type:varchar(30), Default:NULL, Null:NO]
#   * FK_ParameterType    [Type:int(11), Default:0, Null:NO]
#   * psc_id              [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch           [Type:int(11), Default:NULL, Null:YES]
#   * psc_user            [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen          [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod             [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:YES]
#   * psc_restrict        [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_parameter_type
# * has_many lmce_device_categories
# * has_many lmce_device_category_device_datas
# * has_many lmce_device_device_datas
# * has_many lmce_device_template_device_datas
# * has_many lmce_device_templates
# * has_many lmce_devices
# * has_many lmce_dhcp_device_device_datas
# * has_many lmce_dhcp_devices
#

class PlutoMain::LmceDeviceData < PlutoMainDatabase
  set_table_name "DeviceData"
  set_primary_key "PK_DeviceData"

  # foreign key references
  # FK_DeviceData references PlutoMain::LmceParameterType (FK_ParameterType)
  belongs_to  :lmce_parameter_type,
      :class_name => "PlutoMain::LmceParameterType",
      :foreign_key => "FK_ParameterType"

  # n:n via through join table PlutoMain::LmceDeviceTemplateDeviceData  (FK_DeviceData)
  has_many  :lmce_device_template_device_datas,
      :class_name => "PlutoMain::LmceDeviceTemplateDeviceData",
      :foreign_key => "FK_DeviceData"
  has_many  :lmce_device_templates,
      :through => :lmce_device_template_device_datas

  # n:n via through join table PlutoMain::LmceDhcpDeviceDeviceData  (FK_DeviceData)
  has_many  :lmce_dhcp_device_device_datas,
      :class_name => "PlutoMain::LmceDhcpDeviceDeviceData",
      :foreign_key => "FK_DeviceData"
  has_many  :lmce_dhcp_devices,
      :through => :lmce_dhcp_device_device_datas

  # n:n via through join table PlutoMain::LmceDeviceDeviceData  (FK_DeviceData)
  has_many  :lmce_device_device_datas,
      :class_name => "PlutoMain::LmceDeviceDeviceData",
      :foreign_key => "FK_DeviceData"
  has_many  :lmce_devices,
      :through => :lmce_device_device_datas

  # n:n via through join table PlutoMain::LmceDeviceCategoryDeviceData  (FK_DeviceData)
  has_many  :lmce_device_category_device_datas,
      :class_name => "PlutoMain::LmceDeviceCategoryDeviceData",
      :foreign_key => "FK_DeviceData"
  has_many  :lmce_device_categories,
      :through => :lmce_device_category_device_datas

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

