# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_media.AttributeType
#
# * primary keys: PK_AttributeType
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMedia::LmceAttribute
# * PlutoMedia::LmceLongAttribute
# * PlutoMedia::LmceMediaTypeAttributeType
#
# == Database Table Columns
#   * PK_AttributeType    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description         [Type:varchar(50), Default:NULL, Null:NO]
#   * Define              [Type:varchar(50), Default:NULL, Null:YES]
#   * PicPriority         [Type:int(11), Default:NULL, Null:YES]
#   * psc_id              [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch           [Type:int(11), Default:NULL, Null:YES]
#   * psc_user            [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen          [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod             [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict        [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_attribute_type_default_sort
# * has_many lmce_attributes
# * has_many lmce_long_attributes
# * has_many lmce_media_type_attribute_types
# * has_many lmce_media_types
#

require 'pluto_main/lmce_media_type'

include PlutoMain

class PlutoMedia::LmceAttributeType < PlutoMediaDatabase
  set_table_name "AttributeType"
  set_primary_key "PK_AttributeType"

  # foreign key references
  # 1:n  (FK_AttributeType)
  has_many  :lmce_attributes,
      :class_name => "PlutoMedia::LmceAttribute",
      :foreign_key => "FK_AttributeType"

  # 1:n  (FK_AttributeType)
  has_many  :lmce_long_attributes,
      :class_name => "PlutoMedia::LmceLongAttribute",
      :foreign_key => "FK_AttributeType"

  # n:n via through join table PlutoMedia::LmceMediaTypeAttributeType  (FK_AttributeType)
  has_many  :lmce_media_type_attribute_types,
      :class_name => "PlutoMedia::LmceMediaTypeAttributeType",
      :foreign_key => "FK_AttributeType"
      # :through doesn't work when join table is in the same database 
      # but the destination table is not, so use finder_sql
      # :through => :lmce_media_type_attribute_types
  has_many  :lmce_media_types,
      :class_name => "PlutoMain::LmceMediaType",
      :foreign_key => "FK_AttributeType",
      :finder_sql => 'SELECT MediaType.* ' +
          'FROM pluto_main.MediaType ' +
          'INNER JOIN pluto_media.MediaType_AttributeType ' +
          'ON (pluto_main.MediaType.PK_MediaType = pluto_media.MediaType_AttributeType.EK_MediaType) ' +
          'WHERE (MediaType_AttributeType.FK_AttributeType = #{id})'

  # external key references
  # 1:n  (EK_AttributeType_DefaultSort)
  has_many  :lmce_attribute_type_default_sort,
      :class_name => "PlutoMain::LmceMediaType",
      :foreign_key => "EK_AttributeType_DefaultSort"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

