# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_media.SearchToken
#
# * primary keys: PK_SearchToken
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMedia::LmceSearchTokenAttribute
#
# == Database Table Columns
#   * PK_SearchToken    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Token             [Type:varchar(20), Default:NULL, Key:MUL, Null:NO]
#   * psc_id            [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch         [Type:int(11), Default:NULL, Null:YES]
#   * psc_user          [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen        [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod           [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict      [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_attributes
# * has_many lmce_search_token_attributes
#

class PlutoMedia::LmceSearchToken < PlutoMediaDatabase
  set_table_name "SearchToken"
  set_primary_key "PK_SearchToken"

  # foreign key references
  # n:n via through join table PlutoMedia::LmceSearchTokenAttribute  (FK_SearchToken)
  has_many  :lmce_search_token_attributes,
      :class_name => "PlutoMedia::LmceSearchTokenAttribute",
      :foreign_key => "FK_SearchToken"
  has_many  :lmce_attributes,
      :through => :lmce_search_token_attributes

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

