# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_media.RipStatus
#
# * primary keys: PK_RipStatus
# * foreign keys: FK_Disc,FK_File
# * external keys: EK_Device
#
# == References
# * PlutoMedia::LmceDisc
# * PlutoMedia::LmceFile
#
# == Referenced By
#
# == Database Table Columns
#   * PK_RipStatus    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * EK_Device       [Type:int(11), Default:NULL, Null:YES]
#   * Slot            [Type:int(11), Default:NULL, Null:YES]
#   * FK_Disc         [Type:int(11), Default:NULL, Null:YES]
#   * FK_File         [Type:int(11), Default:NULL, Null:YES]
#   * Type            [Type:char(1), Default:NULL, Null:YES]
#   * RipJob          [Type:int(11), Default:NULL, Null:YES]
#   * DateTime        [Type:datetime, Default:NULL, Null:YES]
#   * Status          [Type:char(1), Default:NULL, Null:YES]
#   * Message         [Type:varchar(40), Default:NULL, Null:YES]
#   * File            [Type:varchar(255), Default:NULL, Null:YES]
#   * psc_id          [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch       [Type:int(11), Default:NULL, Null:YES]
#   * psc_user        [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen      [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod         [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict    [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device
# * belongs_to lmce_disc
# * belongs_to lmce_file
#

require 'pluto_main/lmce_device'

include PlutoMain

class PlutoMedia::LmceRipStatus < PlutoMediaDatabase
  set_table_name "RipStatus"
  set_primary_key "PK_RipStatus"

  # foreign key references
  # FK_RipStatus references PlutoMedia::LmceDisc (FK_Disc)
  belongs_to  :lmce_disc,
      :class_name => "PlutoMedia::LmceDisc",
      :foreign_key => "FK_Disc"

  # FK_RipStatus references PlutoMedia::LmceFile (FK_File)
  belongs_to  :lmce_file,
      :class_name => "PlutoMedia::LmceFile",
      :foreign_key => "FK_File"

  # external key references
  # EK_RipStatus references PlutoMain::LmceDevice (EK_Device)
  belongs_to  :lmce_device,
      :class_name => "PlutoMain::LmceDevice",
      :foreign_key => "EK_Device"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

