# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_media.File_Users
# Through Join Table
#
# * primary keys: FK_File,EK_Users
# * foreign keys: FK_File
# * external keys: EK_Users
#
# == References
# * PlutoMedia::LmceFile
#
# == Referenced By
#
# == Database Table Columns
#   * FK_File         [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * EK_Users        [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * UserRating      [Type:tinyint(2), Default:5, Null:YES]
#   * CalcRating      [Type:tinyint(2), Default:5, Null:YES]
#   * psc_id          [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch       [Type:int(11), Default:NULL, Null:YES]
#   * psc_user        [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen      [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod         [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict    [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_file
# * belongs_to lmce_user
#

require 'pluto_main/lmce_user'

include PlutoMain

class PlutoMedia::LmceFileUser < PlutoMediaDatabase
  set_table_name "File_Users"
  set_primary_keys "FK_File", "EK_Users"

  # foreign key references
  # FK_File_Users references PlutoMedia::LmceFile (FK_File)
  belongs_to  :lmce_file,
      :class_name => "PlutoMedia::LmceFile",
      :foreign_key => "FK_File"

  # external key references
  # EK_File_Users references PlutoMain::LmceUser (EK_Users)
  belongs_to  :lmce_user,
      :class_name => "PlutoMain::LmceUser",
      :foreign_key => "EK_Users"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

