# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_media.DiscLocation
#
# * primary keys: EK_Device,Slot
# * foreign keys: FK_Disc
# * external keys: EK_Device,EK_Device_Ripping
#
# == References
# * PlutoMedia::LmceDisc
#
# == Referenced By
#
# == Database Table Columns
#   * EK_Device            [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * Slot                 [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Disc              [Type:int(11), Default:NULL, Null:YES]
#   * Type                 [Type:char(1), Default:NULL, Null:YES]
#   * EK_Device_Ripping    [Type:int(11), Default:NULL, Null:YES]
#   * RipJob               [Type:int(11), Default:NULL, Null:YES]
#   * psc_id               [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch            [Type:int(11), Default:NULL, Null:YES]
#   * psc_user             [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod              [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict         [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device
# * belongs_to lmce_device_ripping
# * belongs_to lmce_disc
#

require 'pluto_main/lmce_device'

include PlutoMain

class PlutoMedia::LmceDiscLocation < PlutoMediaDatabase
  set_table_name "DiscLocation"
  set_primary_keys "EK_Device", "Slot"

  # foreign key references
  # FK_DiscLocation references PlutoMedia::LmceDisc (FK_Disc)
  belongs_to  :lmce_disc,
      :class_name => "PlutoMedia::LmceDisc",
      :foreign_key => "FK_Disc"

  # external key references
  # EK_DiscLocation references PlutoMain::LmceDevice (EK_Device)
  belongs_to  :lmce_device,
      :class_name => "PlutoMain::LmceDevice",
      :foreign_key => "EK_Device"

  # EK_DiscLocation references PlutoMain::LmceDevice (EK_Device_Ripping)
  belongs_to  :lmce_device_ripping,
      :class_name => "PlutoMain::LmceDevice",
      :foreign_key => "EK_Device_Ripping"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

