# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_media.LongAttribute
#
# * primary keys: PK_LongAttribute
# * foreign keys: FK_AttributeType,FK_Disc,FK_File,FK_Attribute
# * external keys: 
#
# == References
# * PlutoMedia::LmceAttribute
# * PlutoMedia::LmceFile
# * PlutoMedia::LmceDisc
# * PlutoMedia::LmceAttributeType
#
# == Referenced By
#
# == Database Table Columns
#   * PK_LongAttribute    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_AttributeType    [Type:int(11), Default:0, Null:NO]
#   * FK_Disc             [Type:int(11), Default:NULL, Null:YES]
#   * FK_File             [Type:int(11), Default:NULL, Null:YES]
#   * FK_Attribute        [Type:int(11), Default:NULL, Null:YES]
#   * Text                [Type:text, Default:NULL, Null:YES]
#   * psc_id              [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch           [Type:int(11), Default:NULL, Null:YES]
#   * psc_user            [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen          [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod             [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict        [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_attribute
# * belongs_to lmce_attribute_type
# * belongs_to lmce_disc
# * belongs_to lmce_file
#

class PlutoMedia::LmceLongAttribute < PlutoMediaDatabase
  set_table_name "LongAttribute"
  set_primary_key "PK_LongAttribute"

  # foreign key references
  # FK_LongAttribute references PlutoMedia::LmceAttribute (FK_Attribute)
  belongs_to  :lmce_attribute,
      :class_name => "PlutoMedia::LmceAttribute",
      :foreign_key => "FK_Attribute"

  # FK_LongAttribute references PlutoMedia::LmceFile (FK_File)
  belongs_to  :lmce_file,
      :class_name => "PlutoMedia::LmceFile",
      :foreign_key => "FK_File"

  # FK_LongAttribute references PlutoMedia::LmceDisc (FK_Disc)
  belongs_to  :lmce_disc,
      :class_name => "PlutoMedia::LmceDisc",
      :foreign_key => "FK_Disc"

  # FK_LongAttribute references PlutoMedia::LmceAttributeType (FK_AttributeType)
  belongs_to  :lmce_attribute_type,
      :class_name => "PlutoMedia::LmceAttributeType",
      :foreign_key => "FK_AttributeType"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

