# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_media.FileFormat
#
# * primary keys: PK_FileFormat
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMedia::LmceFile
# * PlutoMedia::LmceDisc
# * PlutoMedia::LmceMediaTypeFileFormat
# * PlutoMedia::LmceDownload
#
# == Database Table Columns
#   * PK_FileFormat    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description      [Type:varchar(50), Default:NULL, Null:NO]
#   * Define           [Type:varchar(50), Default:NULL, Null:YES]
#   * psc_id           [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch        [Type:int(11), Default:NULL, Null:YES]
#   * psc_user         [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen       [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod          [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict     [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_discs
# * has_many lmce_downloads
# * has_many lmce_files
# * has_many lmce_media_type_file_formats
# * has_many lmce_media_types
#

class PlutoMedia::LmceFileFormat < PlutoMediaDatabase
  set_table_name "FileFormat"
  set_primary_key "PK_FileFormat"

  # foreign key references
  # 1:n  (FK_FileFormat)
  has_many  :lmce_files,
      :class_name => "PlutoMedia::LmceFile",
      :foreign_key => "FK_FileFormat"

  # 1:n  (FK_FileFormat)
  has_many  :lmce_discs,
      :class_name => "PlutoMedia::LmceDisc",
      :foreign_key => "FK_FileFormat"

  # n:n via through join table PlutoMedia::LmceMediaTypeFileFormat  (FK_FileFormat)
  has_many  :lmce_media_type_file_formats,
      :class_name => "PlutoMedia::LmceMediaTypeFileFormat",
      :foreign_key => "FK_FileFormat"
      # :through doesn't work when join table is in the same database 
      # but the destination table is not, so use finder_sql
      # :through => :lmce_media_type_file_formats
  has_many  :lmce_media_types,
      :class_name => "PlutoMain::LmceMediaType",
      :foreign_key => "FK_FileFormat",
      :finder_sql => 'SELECT MediaType.* ' +
          'FROM pluto_main.MediaType ' +
          'INNER JOIN pluto_media.MediaType_FileFormat ' +
          'ON (pluto_main.MediaType.PK_MediaType = pluto_media.MediaType_FileFormat.EK_MediaType) ' +
          'WHERE (MediaType_FileFormat.FK_FileFormat = #{id})'

  # 1:n  (FK_FileFormat)
  has_many  :lmce_downloads,
      :class_name => "PlutoMedia::LmceDownload",
      :foreign_key => "FK_FileFormat"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

