# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_media.SearchToken_Attribute
# Through Join Table
#
# * primary keys: FK_SearchToken,FK_Attribute
# * foreign keys: FK_SearchToken,FK_Attribute
# * external keys: 
#
# == References
# * PlutoMedia::LmceAttribute
# * PlutoMedia::LmceSearchToken
#
# == Referenced By
#
# == Database Table Columns
#   * FK_SearchToken    [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * FK_Attribute      [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * psc_id            [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch         [Type:int(11), Default:NULL, Null:YES]
#   * psc_user          [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen        [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod           [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict      [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_attribute
# * belongs_to lmce_search_token
#

class PlutoMedia::LmceSearchTokenAttribute < PlutoMediaDatabase
  set_table_name "SearchToken_Attribute"
  set_primary_keys "FK_SearchToken", "FK_Attribute"

  # foreign key references
  # FK_SearchToken_Attribute references PlutoMedia::LmceAttribute (FK_Attribute)
  belongs_to  :lmce_attribute,
      :class_name => "PlutoMedia::LmceAttribute",
      :foreign_key => "FK_Attribute"

  # FK_SearchToken_Attribute references PlutoMedia::LmceSearchToken (FK_SearchToken)
  belongs_to  :lmce_search_token,
      :class_name => "PlutoMedia::LmceSearchToken",
      :foreign_key => "FK_SearchToken"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

