# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_media.MediaSubType
#
# * primary keys: PK_MediaSubType
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
# * PlutoMedia::LmceDownload
# * PlutoMedia::LmceMediaTypeMediaSubType
# * PlutoMedia::LmceFile
# * PlutoMedia::LmceDisc
#
# == Database Table Columns
#   * PK_MediaSubType    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Description        [Type:varchar(50), Default:NULL, Null:NO]
#   * Define             [Type:varchar(50), Default:NULL, Null:YES]
#   * psc_id             [Type:int(11), Default:NULL, Key:UNI, Null:YES]
#   * psc_batch          [Type:int(11), Default:NULL, Null:YES]
#   * psc_user           [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen         [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod            [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict       [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * has_many lmce_discs
# * has_many lmce_downloads
# * has_many lmce_files
# * has_many lmce_media_type_media_sub_types
# * has_many lmce_media_types
#

class PlutoMedia::LmceMediaSubType < PlutoMediaDatabase
  set_table_name "MediaSubType"
  set_primary_key "PK_MediaSubType"

  # foreign key references
  # 1:n  (FK_MediaSubType)
  has_many  :lmce_downloads,
      :class_name => "PlutoMedia::LmceDownload",
      :foreign_key => "FK_MediaSubType"

  # n:n via through join table PlutoMedia::LmceMediaTypeMediaSubType  (FK_MediaSubType)
  has_many  :lmce_media_type_media_sub_types,
      :class_name => "PlutoMedia::LmceMediaTypeMediaSubType",
      :foreign_key => "FK_MediaSubType"
      # :through doesn't work when join table is in the same database 
      # but the destination table is not, so use finder_sql
      # :through => :lmce_media_type_media_sub_types
  has_many  :lmce_media_types,
      :class_name => "PlutoMain::LmceMediaType",
      :foreign_key => "FK_MediaSubType",
      :finder_sql => 'SELECT MediaType.* ' +
          'FROM pluto_main.MediaType ' +
          'INNER JOIN pluto_media.MediaType_MediaSubType ' +
          'ON (pluto_main.MediaType.PK_MediaType = pluto_media.MediaType_MediaSubType.EK_MediaType) ' +
          'WHERE (MediaType_MediaSubType.FK_MediaSubType = #{id})'

  # 1:n  (FK_MediaSubType)
  has_many  :lmce_files,
      :class_name => "PlutoMedia::LmceFile",
      :foreign_key => "FK_MediaSubType"

  # 1:n  (FK_MediaSubType)
  has_many  :lmce_discs,
      :class_name => "PlutoMedia::LmceDisc",
      :foreign_key => "FK_MediaSubType"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

