# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_media.Download
#
# * primary keys: PK_Download
# * foreign keys: FK_DownloadSource,FK_MediaSubType,FK_FileFormat
# * external keys: EK_MediaType
#
# == References
# * PlutoMedia::LmceFileFormat
# * PlutoMedia::LmceDownloadSource
# * PlutoMedia::LmceMediaSubType
#
# == Referenced By
# * PlutoMedia::LmcePictureDownload
# * PlutoMedia::LmceDownloadAttribute
#
# == Database Table Columns
#   * PK_Download          [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_DownloadSource    [Type:int(11), Default:0, Null:NO]
#   * EK_MediaType         [Type:int(11), Default:0, Null:NO]
#   * FK_MediaSubType      [Type:int(11), Default:NULL, Null:YES]
#   * FK_FileFormat        [Type:int(11), Default:NULL, Null:YES]
#   * MRL                  [Type:varchar(255), Default:NULL, Null:YES]
#   * psc_id               [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch            [Type:int(11), Default:NULL, Null:YES]
#   * psc_user             [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen           [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod              [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict         [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_download_source
# * belongs_to lmce_file_format
# * belongs_to lmce_media_sub_type
# * belongs_to lmce_media_type
# * has_many lmce_attributes
# * has_many lmce_download_attributes
# * has_many lmce_picture_downloads
# * has_many lmce_pictures
#

require 'pluto_main/lmce_media_type'

include PlutoMain

class PlutoMedia::LmceDownload < PlutoMediaDatabase
  set_table_name "Download"
  set_primary_key "PK_Download"

  # foreign key references
  # FK_Download references PlutoMedia::LmceFileFormat (FK_FileFormat)
  belongs_to  :lmce_file_format,
      :class_name => "PlutoMedia::LmceFileFormat",
      :foreign_key => "FK_FileFormat"

  # FK_Download references PlutoMedia::LmceDownloadSource (FK_DownloadSource)
  belongs_to  :lmce_download_source,
      :class_name => "PlutoMedia::LmceDownloadSource",
      :foreign_key => "FK_DownloadSource"

  # FK_Download references PlutoMedia::LmceMediaSubType (FK_MediaSubType)
  belongs_to  :lmce_media_sub_type,
      :class_name => "PlutoMedia::LmceMediaSubType",
      :foreign_key => "FK_MediaSubType"

  # n:n via through join table PlutoMedia::LmcePictureDownload  (FK_Download)
  has_many  :lmce_picture_downloads,
      :class_name => "PlutoMedia::LmcePictureDownload",
      :foreign_key => "FK_Download"
  has_many  :lmce_pictures,
      :through => :lmce_picture_downloads

  # n:n via through join table PlutoMedia::LmceDownloadAttribute  (FK_Download)
  has_many  :lmce_download_attributes,
      :class_name => "PlutoMedia::LmceDownloadAttribute",
      :foreign_key => "FK_Download"
  has_many  :lmce_attributes,
      :through => :lmce_download_attributes

  # external key references
  # EK_Download references PlutoMain::LmceMediaType (EK_MediaType)
  belongs_to  :lmce_media_type,
      :class_name => "PlutoMain::LmceMediaType",
      :foreign_key => "EK_MediaType"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

