# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_myth.DTV_Channel
#
# * primary keys: PK_DTV_Channel
# * foreign keys: FK_Provider
# * external keys: 
#
# == References
# * PlutoMyth::LmceProvider
#
# == Referenced By
#
# == Database Table Columns
#   * PK_DTV_Channel    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_Provider       [Type:int(11), Default:0, Null:NO]
#   * Callsign          [Type:varchar(10), Default:NULL, Null:NO]
#   * Frequency         [Type:varchar(10), Default:NULL, Null:NO]
#   * Modulation        [Type:varchar(10), Default:NULL, Null:NO]
#   * APID              [Type:int(11), Default:0, Null:NO]
#   * VPID              [Type:int(11), Default:0, Null:NO]
#   * TPID              [Type:int(11), Default:0, Null:NO]
#   * psc_id            [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch         [Type:int(11), Default:NULL, Null:YES]
#   * psc_user          [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen        [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod           [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict      [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_provider
#

class PlutoMyth::LmceDtvChannel < PlutoMythDatabase
  set_table_name "DTV_Channel"
  set_primary_key "PK_DTV_Channel"

  # foreign key references
  # FK_DTV_Channel references PlutoMyth::LmceProvider (FK_Provider)
  belongs_to  :lmce_provider,
      :class_name => "PlutoMyth::LmceProvider",
      :foreign_key => "FK_Provider"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

