# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_myth.psc_myth_schema
#
# * primary keys: PK_psc_myth_schema
# * foreign keys: 
# * external keys: 
#
# == References
#
# == Referenced By
#
# == Database Table Columns
#   * PK_psc_myth_schema    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * Value                 [Type:text, Default:NULL, Null:NO]
#
# == Associations
#

class PlutoMyth::LmcePscMythSchema < PlutoMythDatabase
  set_table_name "psc_myth_schema"
  set_primary_key "PK_psc_myth_schema"


  # add your model extensions after this line

end

