# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_myth.Picture
#
# * primary keys: EK_Picture
# * foreign keys: 
# * external keys: EK_Picture
#
# == References
#
# == Referenced By
#
# == Database Table Columns
#   * EK_Picture      [Type:int(11), Default:0, Key:PRI, Null:NO]
#   * chanid          [Type:int(11), Default:NULL, Key:MUL, Null:YES]
#   * seriesid        [Type:varchar(12), Default:NULL, Key:MUL, Null:YES]
#   * programid       [Type:varchar(20), Default:NULL, Key:MUL, Null:YES]
#   * psc_id          [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch       [Type:int(11), Default:NULL, Null:YES]
#   * psc_user        [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen      [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod         [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict    [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_picture
# * has_many lmce_device_quick_starts
# * has_one lmce_picture
#

require 'pluto_main/lmce_device_quick_start'
require 'pluto_myth/lmce_picture'

include PlutoMain
include PlutoMyth

class PlutoMyth::LmcePicture < PlutoMythDatabase
  set_table_name "Picture"
  set_primary_key "EK_Picture"

  # external key references
  # EK_Picture references PlutoMyth::LmcePicture (EK_Picture)
  belongs_to  :lmce_picture,
      :class_name => "PlutoMyth::LmcePicture",
      :foreign_key => "EK_Picture"

  # 1:n  (EK_Picture)
  has_many  :lmce_device_quick_starts,
      :class_name => "PlutoMain::LmceDeviceQuickStart",
      :foreign_key => "EK_Picture"

  # 1:1  (EK_Picture)
  has_one  :lmce_picture,
      :class_name => "PlutoMyth::LmcePicture",
      :foreign_key => "EK_Picture"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

