# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_security.ModeChange
#
# * primary keys: PK_ModeChange
# * foreign keys: 
# * external keys: EK_HouseMode,EK_DeviceGroup,EK_Users
#
# == References
#
# == Referenced By
#
# == Database Table Columns
#   * PK_ModeChange     [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * EK_HouseMode      [Type:int(11), Default:0, Null:NO]
#   * EK_DeviceGroup    [Type:int(11), Default:NULL, Null:YES]
#   * ChangeTime        [Type:datetime, Default:0000-00-00, Null:NO]
#   * EK_Users          [Type:int(11), Default:NULL, Null:YES]
#   * psc_id            [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch         [Type:int(11), Default:NULL, Null:YES]
#   * psc_user          [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen        [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod           [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict      [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_device_group
# * belongs_to lmce_house_mode
# * belongs_to lmce_user
#

require 'pluto_main/lmce_device_group'
require 'pluto_main/lmce_house_mode'
require 'pluto_main/lmce_user'

include PlutoMain

class PlutoSecurity::LmceModeChange < PlutoSecurityDatabase
  set_table_name "ModeChange"
  set_primary_key "PK_ModeChange"

  # external key references
  # EK_ModeChange references PlutoMain::LmceUser (EK_Users)
  belongs_to  :lmce_user,
      :class_name => "PlutoMain::LmceUser",
      :foreign_key => "EK_Users"

  # EK_ModeChange references PlutoMain::LmceDeviceGroup (EK_DeviceGroup)
  belongs_to  :lmce_device_group,
      :class_name => "PlutoMain::LmceDeviceGroup",
      :foreign_key => "EK_DeviceGroup"

  # EK_ModeChange references PlutoMain::LmceHouseMode (EK_HouseMode)
  belongs_to  :lmce_house_mode,
      :class_name => "PlutoMain::LmceHouseMode",
      :foreign_key => "EK_HouseMode"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

