# Copyright 2008 by Roy Wright
# License: GPL version 2 (http://www.opensource.org/licenses/gpl-2.0.php)
# generated by mysql2models.rb 0.2 Tue Jun 17 01:17:05 -0500 2008
#
# == Synopsis
# Database Table: pluto_security.Alert_Device
# Through Join Table
#
# * primary keys: PK_Alert_Device
# * foreign keys: FK_Alert
# * external keys: EK_Device
#
# == References
# * PlutoSecurity::LmceAlert
#
# == Referenced By
#
# == Database Table Columns
#   * PK_Alert_Device    [Type:int(11), Default:NULL, Key:PRI, Null:NO, Extra:auto_increment]
#   * FK_Alert           [Type:int(11), Default:0, Null:NO]
#   * EK_Device          [Type:int(11), Default:0, Null:NO]
#   * DetectionTime      [Type:datetime, Default:0000-00-00, Null:NO]
#   * psc_id             [Type:int(11), Default:NULL, Null:YES]
#   * psc_batch          [Type:int(11), Default:NULL, Null:YES]
#   * psc_user           [Type:int(11), Default:NULL, Null:YES]
#   * psc_frozen         [Type:tinyint(1), Default:0, Null:YES]
#   * psc_mod            [Type:timestamp, Default:CURRENT_TIMESTAMP, Null:NO]
#   * psc_restrict       [Type:int(11), Default:NULL, Null:YES]
#
# == Associations
# * belongs_to lmce_alert
# * belongs_to lmce_device
#

require 'pluto_main/lmce_device'

include PlutoMain

class PlutoSecurity::LmceAlertDevice < PlutoSecurityDatabase
  set_table_name "Alert_Device"
  set_primary_key "PK_Alert_Device"

  # foreign key references
  # FK_Alert_Device references PlutoSecurity::LmceAlert (FK_Alert)
  belongs_to  :lmce_alert,
      :class_name => "PlutoSecurity::LmceAlert",
      :foreign_key => "FK_Alert"

  # external key references
  # EK_Alert_Device references PlutoMain::LmceDevice (EK_Device)
  belongs_to  :lmce_device,
      :class_name => "PlutoMain::LmceDevice",
      :foreign_key => "EK_Device"

  # handle psc_mod timestamping

# Set the psc_mod timestamp to the current time when creating a record.
  def before_create
    self.psc_mod ||= Time.now
  end

# Set the psc_mod timestamp to the current time when updating a record.
  def before_update
    self.psc_mod = Time.now
  end

  # add your model extensions after this line

end

